import { Component, OnInit, ViewChild } from '@angular/core';
import { africaMap, nigeriaMap, worldMap } from "../../world-map";
import * as $ from 'jquery'
import { DummyData } from '../../population-data';
import { economicData, economicData2 } from 'src/app/economy-data';
declare var require: any;

export const vaccine = `
ABIA	ABA NORTH	 EZIAMA PUBLIC HEALTH CLINIC
| URATTA PRIMARY HEALTH CENTRE
ABIA	ABA SOUTH	 HEALTH OFFICE MATERNAL AND CHILD HEALTH CENTER
|GENERAL HOSPITAL
ABIA	AROCHUKWU	 COLLEGE OF HEALTH CENTRE
| HEALTH OFFICE CLINIC
ABIA	BENDE	OZUABAM HEALTH CENTRE
|UZUAKOLI PRIMARY HEALTH CENTRE
ABIA	IKWUANO	IGBERE PRIMARY HEALTH CENTRE
|UMUGBALU PRIMARY HEALTH CENTRE
ABIA	ISIALA NGWA NORTH	ARIAM PRIMARY HEALTH CENTRE
|OKPULA NGWA PRIMARY HEALTH CENTRE
ABIA	ISIALA NGWA SOUTH	NTIGHA OKPUALA HEALTH CENTRE
|UMUOSU HEALTH POST
|HEALTH OFFICE CLINIC
ABIA	ISUIKWUATO	UGBA PRIMARY HEALTH CENTRE
|OVIM PRIMARY HEALTH CENTRE
ABIA	OBINGWA	MGBAUGWU PRIMARY HEALTH CENTRE
|OBI NGWA HEADQUARTERS HEALTH CLINIC
ABIA	OHAFIA	OSUSU AMUKWA HEALTH POST
|LGA HEALTH CENTRE
ABIA	OSISIOMA	OHAFOR PRIMARY HEALTH CENTER
|OSISIOMA HEALTH OFFICE PRIMARY HEALTH CENTRE
ABIA	UGWUNAGBO	UMUODE PRIMARY HEALTH CENTRE
|UGWUNAGBO PRIMARY HEALTH CENTER
ABIA	UKWA EAST	ISIALA IHIE PRIMARY HEALTH CENTER
|AKWETE PRIMARY HEALTH CENTRE
ABIA	UKWA WEST	AZUMINI PRIMARY HEALTH CENTRE
|OBEHIE PRIMARY HEALTH CARE
ABIA	UMUAHIA NORTH	OGWE PRIMARY HEALTH CARE
|INFANT WELFARE CLINIC
ABIA	UMUAHIA SOUTH	FEDERAL MEDICAL CENTRE UMUAHIA
|AMUZUKWU HEALTH CENTRE
|ISIAMA AFARA HEALTH CENTRE
|WORLD BANK HEALTH CENTRE
|UBAKALA PRIMARY HEALTH CARE
ABIA	UMUNNEOCHI	EKENOBIZI PRIMARY HEALTH CENTRE
|EZINGODOPRIMARY HEALTH CENTRE
|UHUOLOGHU HEALTH CENTRE
|
ADAMAWA	DEMSA	BORRONG PHC
|DEMSA PHCC
ADAMAWA	FUFORE	FUFORE PHCC
|PARIYA PHCC
ADAMAWA	GANYE 	GENERAL HOSPITAL GANYE
|JAGGU PHCC
|YELWA PHC
ADAMAWA	GIREI	DAKRI PHCC
|GIREI B PHC
ADAMAWA	GOMBI 	CLINIC B GOMBI
|MUCHALA PHC
ADAMAWA	GUYUK	BANJIRAM PHC
ADAMAWA	HONG	GENERAL HOSPITAL HONG
|PELLA WOMEN IN HEALTH
|UBA PHC
ADAMAWA	JADA 	GENERAL HOSPITAL JADA
|KOJOLI PHC
|MBULO PHC
ADAMAWA	LAMURDE	GYAWANA PHC 
|LAMURDE PHC
ADAMAWA	MADAGALI	SHUWA MISSION HC
|COTTAGE HOSPITAL GULAK
|MADAGALI PHCC
ADAMAWA	MAIHA	PAKKA PHC
|BELEL PHC
ADAMAWA	MAYO BELWA	JERENG PHCC
|MAYO BELWA PHCC
|TOLA PHC
ADAMAWA	MICHIKA	BAZZA PHCC
|MICHIKA TOWN CLINIC
ADAMAWA	MUBI NORTH	LOKUWA PHCC
|BAHULI PHCC
|MUCHALA PHC
ADAMAWA	MUBI SOUTH	MUGULBU PHCC
|GENERAL HOSPITAL MUBI 
ADAMAWA	NUMAN	SABON PEGI PHC
ADAMAWA	SHELLENG	NYSC CLINIC SHELLENG
ADAMAWA	SONG	DUMNE PHCC
|COTTAGE HOSPITAL SONG
ADAMAWA	TOUNGO	COTTAGE HOSPITAL TOUNGO
ADAMAWA	YOLA NORTH	MALARE PHC
|YOLA SPECIAL LIST 
|JAMBUTU PHCC
|YELWA PHC
ADAMAWA	YOLA SOUTH	FMC YOLA
|NANA ASMAU PHCC
|NAMTARI MANGA PHCC
ANAMABRA	OYI	NTEJE 4 PHC
|AWKUZU 4 PHC
|
AKWA IBOM	ABAK	ABAK OPERATIONAL BASE PRIMARY HEALTH CENTRE
|ABAK MERCY HOSPITAL 
AKWA IBOM	EASTERN OBOLO	OKOROETTE PRIMARY HEALTH CENTER
AKWA IBOM	EKET	EKET PRIMARY HEALTH CENTER OPERATIONAL BASE
|IMMANUEL GENERAL HOSPITAL 
AKWA IBOM	EKSIT  EKET	UQUO TOWN OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	ESSIEN UDIM	UKANA EAST PRIMARY HEALTH CENTRE
AKWA IBOM	ETIM EKPO	URUK ATA IKOT EKPOR PRIMARY HEALTH CENTRE 
AKWA IBOM	ETINAN	ETINAN PRIMARY HEALTH CENTRE OPERATIONAL BASE 
|ETINAN GENERAL HOSPITAL 
AKWA IBOM	IBENO	UKPENEKANG OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	IBESIKPO ASUTAN	NUNG UDOE PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	IBIONO IBOM	IKPA PRIMARY HEALTH CENTRE OPERATIONAL BASE
|USE ABAT ST THERESA'S HOSPITAL 
AKWA IBOM	IKA	URUA INYANG OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	IKONO	IBIAKU NTOK OKPO PRIMARY HEALTH CENTRE
AKWA IBOM	IKOT ABASI	IKOT ABASI OPERATIONAL BASE PRIMARY HEALTH CENTRE
|ESSENE COMPREHENSIVE HEALTH CENTRE
AKWA IBOM	IKOT EKPENE	IKOT EKPENE PRIMARY HEALTH CENTRE OPERATIONAL BASE 
|GENERAL HOSPITAL IKOT EKPENE
AKWA IBOM	INI	ODORO IKPE PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	ITU	MBAK ATAI PRIMARY HEALTH OPERATIONAL BASE  
|NTAK INYANG HEALTH CENTRE
AKWA IBOM	MBO	ENWANG PRIMARY HEALTH CENTRE OPERATIONAL BASE 
AKWA IBOM	EKPAT ENIN	MKPAT ENIN PRIMARY  HEALTH CENTRE OPERATIONAL BASE
|IKOT EKPE COMPREHENSIVE HEALTH CENTRE 
AKWA IBOM	NSIT ATAI	ODOT PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	NSIT  IBOM	AFAHA OFFIONG OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	NSIT  IBIUM	IKOT EDIBON OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	OBOT AKARA	NTO EDINO PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	OKOBO	OKOPEDI PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	ONNA	ABAT PRIMARY HEALTH CENTRE OPERATIONAL BASE
|AWA COMPREHENSIVE HEALTH CENTRE
AKWA IBOM	ORON	ORON PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	ORUK ANAM	IKOT IBRITAM PRIMARY HEALTH CARE CENTRE OPERATIONAL BASE
|IKOT OKORO GENERAL HOSPITAL 
AKWA IBOM	UDUNG UKO	EYOFIN PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	UKANAFUN	IKOT AKPA NKUK PRIMARY HEALTH CENTRE OPERATIONAL BASE
AKWA IBOM	URUAN	IDU PRIMARY HEALTH CENTRE OPERATIONAL BASE
|METH HOSPITAL ITUKMBANG
AKWA IBOM	URUE-OFFONG/ORUKO	URUE OFFONG OPERATIONAL BASE PRIMARY HEALTH CENTRE
AKWA IBOM	UYO	UYO PRIMARY HEALTH CENTRE OPERATIONAL BASE
|IKOT AKPAN ABIA POLICE MEDICAL CENTRE  AND UYO TEACHING HOSPITAL                   
|
ANAMABRA	AGUATA	PHC AGUATA
|GENERAL HOSP. EKWULOBIA
ANAMABRA	ANAMBRA EAST	MCH OTUOCHA
|ABATA NSUGBE PHC
ANAMABRA	ANAMBRA WEST	UMUDEZE PHC
|NZAM PHC
ANAMABRA	ANAOCHA	TEACHING HOSPITAL NENI
|PHC ICHIDA
|MPHC AMATUTU- 1
ANAMABRA	AWKA NORTH	PHC MGBAKWU
|MCH ACHALLA
ANAMABRA	AWKA SOUTH	COOUTH, AMAKU AWKA
|MCH AMAWBIA
|PHC OKPUNO
|PHC NIBO-2
ANAMABRA	AYAMELUM	ANAKU PHC
|IFITE OGWARI PHC
ANAMABRA	DUNUKOFIA	IRUZU PHC
|UKWULU PHC
ANAMABRA	EKWUSIGO	PHC IBOLO
|REFERRAL HEALTH CENTER, ICHI
ANAMABRA	IDEMILI NORTH	MCH OGIDI
|EZIOWELLE PHC
|PHC AWADA-1
ANAMABRA	IDEMILI SOUTH	PHC OBA
|PHC EBENESI
|PHC AWKA ETITI- 1
ANAMABRA	IHIALA	EZIANI PHC
|PHC ORSUMOGHO
ANAMABRA	NJIKOKA	URUOGBO PHC
|PHC ABAGANA
ANAMBRA	NNEWI NORTH	UMUDIM 2, OKPUNOEGBU PHC
|OTOLO 1, PHC OKPUNO OTOLO
|NAUTH-NNEWI NORTH - 1
ANAMBRA	NNEWI SOUTH	MCH UHUORI UKPOR
|AMICHI PHC
ANAMBRA	OGBARU	PHC OKPOKO 2
|PHC OKPOKO 1
ANAMBRA	ONITSHA NORTH	GENERAL HOSP. ONITSHA
|INLAND TOWN PHC
|OMAGBA PHC- 1
ANAMBRA	ONITSHA SOUTH	PHC UMUNNA
|ST JOHN ANGLICAN PHC
|ST JOHN DE BAPTIST HF- 1
ANAMBRA	ORUMBA NORTH	MCH AJALLI
|PHC NANKA
|MCH UMUNZE
|CHC LOMU
ANAMBRA	OYI	NTEJE 4 PHC
|AWKUZU 4 PHC
|
BAUCHI	ALKALER	YALWAN DUGURI PHC
|FUTUK PHC
|GENERAL HOSPITAL
|GORONDO PHC
BAUCHI	BAUCHI	ATBU TH
|STATE LOW COST
|BAUAN FADA PHC
|WOME & CHILDREN CLINIC
|KANGERE PHC
|LIMAN KATAGUM 
|URBAN MATERNITY
|TRIWUN PHC
|MIRI PHC
|NASARAWA JAHUN PHC
|SPECIALIST HOSPITAL
|TUDUN GAMBO PHC
|YALWAN DOMICILIARY 
BAUCHI	BOGORO	BOI
|GENERAL HOSPITAL
BAUCHI	DAMBAM	JALAM PHC
|DAMBAM PHC
|DAGAU PHC
BAUCHI	DARAZO	AIY UNDER 5 CLINIC
|KWANKIYAL PHC
BAUCHI	GAMAWA	SADE PHC
|BUNUNU TOWN MPHCC
BAUCHI	GANJUWA	LUKSHI PHC
|GENERAL HOSPITAL
|UDUBU PHC
|PHCC KAFIN MADAKI
|GWALOLO PHC
BAUCHI	GIADE	MIYA MPHC
|GENERAL HOSPITAL
BAUCHI	ITAS/GADAU	ZABI MPHC
|PHCC ATAFOWA
|GADAU PHC
BAUCHI	JAMA'ARE	ITAS PHC
|JABBORI PHC
BAUCHI	KATAGUM	GENERAL HOSPITAL
|FEDERAL MEDICAL CENTER
|GENERAL HOPITAL
|URBAN MATERNITY
BAUCHI	KIRFI	BULKACHIWA  MPHC
|WANKA PHC
BAUCHI	MISAU	GUYABA PHC
|KUKADI B
|HARDAWA PHC
BAUCHI	NINGI	AKUYAM PHC
|GENERAL HOSPITAL
|JIMI PHC
BAUCHI	SHIRA	GENERAL BURA 
|PHC YANA
BAUCHI	TAFAWA BALEWA	BUNUNU COTTAGE
|GENERAL HOSPITAL T/BALEWA
BAUCHI	TORO	 PHC LERE
|TILDE PHCC
|GUMA
|GENERAL HOSPITAL
BAUCHI	WARJI	NABARDO PHC
|KATANGA PHC
BAUCHI	ZAKI	TUDUN WADA PHC
|SAKUWA PHC
|LODIYO PHC
|
BAYELSA	BRASS	CHC TWON BRASS
|PHC EGWEAMA
BAYELSA	EKEREMOR	EKEREMOR PHC
|ALEIBIRI PHC
|PERETORUGBENE PHC
BAYELSA	KOLOKUMA/OPOKUMA	BETHLEHEM PHC
|SABAGREIA PHC
|KAIAMA CHC
BAYELSA	NEMBE	TOMBI PHC
|BASSAMBIRI NEMBE PHC
|NEMBE PHC
BAYELSA	OGBIA	OGBIA PHC
|ONUEBUM PHC
|FMC OTUOKE
BAYELSA	SAGBAMA	SAGBAMA PHC
|AKEDDEI PHC
|OGOBIRI PHC
BAYELSA	SOUTHERN IJAW	OGBOINBIRI PHC
|OPOROMA PHC
|AMASSOMA PHC
BAYELSA	YENAGOA	FMC YENAGOA
|FSP CLINIC
|AMARATA PHC
|YENIZUEGENE PHC
|AGUDAMA PHC
|AZIKORO PHC
|NIGER DELTA UNIVERSITY TEACHING HOSPITAL
|GOVERNMENT HOUSE SPECIALIST CLINIC
|
BENUE	ADO	PHC ETENYI
|CHC UTONKON
BENUE	AGATU	PHC USHA
|CHC OBAGAJI
BENUE	APA	CHC IGAH
|CHC UGBOKPO
BENUE	BURUKU	PHC TYOWANYE
|GENERAL HOSPITAL BURUKU
BENUE	GBOKO	PHC GBOKO SOUTH
|PHC AMELADU
|PHC AKPAGHER
|PHC TSE AKEME
|PHC WOHYEV
|PHC TSEKUCHA
|CHC GBOKO
BENUE	GUMA	PHC DAUDU
|GENERAL HOSPITAL GBAJIMBA
BENUE	GWER EAST	PHC TARAKU
|CHC ALIADE
BENUE	GWER WEST	CHC IKYAGHEV
|CHC NAKA
BENUE	KATSINA ALA	PHC ABAJI
|GENERAL HOSPITAL KATSINA ALA
|PHC TYOATE
BENUE	KONSHIHSA	GENERAL HOSPITAL TSEAGBERAGBA
BENUE	KWANDE	PHC JATO AKA
|PHC KOTI
|GENERAL HOSPITAL ADIKPO
BENUE	LOGO	PHC ANYIIN
|CHC UGBA
BENUE	MAKURDI	NAF MEDICAL CENTRE MAKURDI
|BENUE STATE UNIVERSITY TEACHING HOSPITAL
|PHC ASASE
|72 PARA MEDICAL CENTRE
|PHC WADATA
|PHC ADEKA
|FSP/MCH MAKURDI
|POLICE CLINIC MAKURDI
BENUE	OBI	PHC IGBEGI
|PHC ITAKPA
BENUE	OGBADIBO	BHC OWUKPA
|OLACHAGBAHA PHC
BENUE	OHIMINI	CHC IDEKPA
BENUE	OJU	PHC OCHODU
|GENERAL HOSPITAL OJU
BENUE	OKPOKWU	PHC UGBOKOLO
|PHC UGWU
BENUE	OTUKPO	ROYAL SPECIALIST HOSPITAL
|ST DANIEL HOSPITAL
|PHC OTOBI
|PHC OTUKPO
|PHC OLAKPOGA
|SEV-AV FOUNDATION CLINIC
BENUE	TARKA	PHC GWARCHE
| 
BENUE	UKUM	PHC GBAGIR
|PHC TOWNSHIP ZAKI BIAM
BENUE	USHONGO	CHC USHONGO
|GENERAL HOSPITAL LESSEL
BENUE	VANDEIKYA	PHC ITYEMIMONGO
|PHC GBAGIR
|CHC USHONGO
|GENERAL HOSPITAL VANDEIKYA
|
BORNO	ASKIRA UBA	YIMIR ALI HEALTH CLINIC
|UBA PRIMARY HEALTH CENTRE
|LASSA GENERAL HOSPITAL
BORNO	BAMA	BANKI HEALTH CLINIC
|BAMA MATERNAL AND CHILD REFERRAL CENTRE
BORNO	BAYO	BRIYEL GENERAL HOSPITAL
|WUYO PRIMARY HEALTH CARE CENTRE
BORNO	BIU	BIU MATERNAL AND CHILD HEALTH CENTRE
|GUNDA PRIMARY HEALTH CENTRE
|MIRINGA MATERNAL AND CHILD HEALTH CLINIC
|BIU GENERAL HOSPITAL
BORNO	CHIBOK	MBALALA PRIMARY HEALTH CENTRE
|GARU GENERAL HOSPITAL 
BORNO	DAMBOA	DAMBOA PRIMARY HEALTH CENTRE
BORNO	DIKWA	DIKWA PRIMARY HEALTH CARE CENTRE 
BORNO	GUBIO	GUBIO MATERNAL AND CHILD HEALTH CENTRE
BORNO	GWOZA	GWOZA WAGANI IDP CAMP CLINIC
|PULKA PRIMARY HEALTH CENTRE
BORNO	HAWUL	SAKWA PRIMARY HEALTH CENTRE
|AZARE GENERAL HOSPITAL
BORNO	JERE	JIDDARI POLO PRIMARY HEALTH CENTRE
|DALARAM PRIMARY HEALTH CENTRE
|UMAR SHEHU ULTRA MODERN HOSPITAL  
|MAIDUGURI UNIVERSITY TEACHING HOSPITAL
BORNO	KAGA	BENESHEIK MATERNAL AND CHILD HEALTH CLINIC
BORNO	KALA BALGE	GENERAL HOSPITAL RANN
BORNO	KUKAWA	BAGA HEALTH CLINIC
BORNO	KODUNGA	POMPOMARI HEALTH CLINIC
|NAF CLINIC
|KONDUGA MATERNAL AND CHILD HEALTH CLINIC
BORNO	KWAYA KUSAR	KWAYA KUSAR MATERNAL AND CHILD HEALTH
|KWAYAKUSAR GENERAL HOSPITAL
BORNO	MAFA	KALERI PRIMARY HEALTH CENTRE
BORNO	MAGUMERI	MAGUMERI MATERNAL AND CHILD HEALTH CLINIC
BORNO	MARTE	NEW MARTE MATERNAL AND CHILD HEALTH CLINIC
BORNO	MAIDUGURI	MALA KACHALLA PRIMARY HEALTH CENTRE
|GWAGE PRIMARY HEALTH CENTRE 
|MAMMAN SHUWA MEMORIAL HOSP. 
|FATIMA ALI SHERIFF  PRIMARY HEALTH CLINIC
|MAIDUGURI STATE SPECIALIST HOSP. 
|MAIDUGURI NEWRO PSYCHIATRIC HOSPITAL
BORNO	MOBBAR	DAMASAK MATERNAL AND CHILD HEALTH
BORNO	MONGUNO	FAMILY SUPPORT PROGRAMME ICRC CLINIC 
|MONGUNO GENERAL HOSPITAL
BORNO	NGALA	GAMBORU MATERNAL AND CHILD HEALTH CENTRE
BORNO	NGAZAI	GAJIRM MATERNAL AND CHILD HEALTH CENTRE
BORNO	SHANI	BARGU PRIMARY HEALTH CARE CENTRE
|SHANI PRIMARY HEALTH CARE CENTRE
|
CROSS RIVER	ABI	PHC ITIGIDI
|PHC EDIBA
CROSS RIVER	AKAMKPA	PHC MMA EFFA
|PHC MFAMOSING
|PHC NYAJE
CROSS RIVER	AKPABUYO	PHC IKOT OFFIONG AMBAI
|PHC IDUNDU
CROSS RIVER	BAKASSI	PHC IKANG
CROSS RIVER	BEKWARRA	MPHC ABUOCHICHE
|PHC UKPAH
CROSS RIVER	BIASE	PHC AKPET
|PHC ADIM
|PHC EHOM
CROSS RIVER	BOKI	CHC OKONDI
|PHC ABO
|PHC BUNYIA
CROSS RIVER	CALABAR MUNICIPAL	PHC EDIBA
|PHC IKOT ANSA
|PCH IKOT OMIN
|PHC BIG QUA
|UNIVERSITY OF CALABAR TEACHING HOSPITAL
CROSS RIVER	CALABAR SOUTH	PHC HENSHAW TOWN
|PHC ANANTIGHA
|PHC NESLSON MANDELA
CROSS RIVER	ETUNG	MPHC EFFRIYA
|PHC BENDEGHE
CROSS RIVER	IKOM	CHC IKOM
|PHC ADIJINKPOR
|PHC EMANGHABE
CROSS RIVER	OBUBRA 	GEN. HOSP. OBUBRA URBAN
|PHC OFATURA
|PHC IYAMOYONG
CROSS RIVER	OBANLIKU	CHC SANKWALA
|PHC BAYAYAM
|PHC UTANGA
CROSS RIVER	OBUDU	PHC OBUDU URBAN
|PHC OHONG
|PHC UTUGWANG
CROSS RIVER	ODUKPANI	PHC ODUKPANI QUO
|PHC CREEK TOWN
|PHC AKPAB
CROSS RIVER	OGOJA	MCH OGOJA
|PHC UKPE
|PHC EKUMTAK
CROSS RIVER	YAKURR	PHC IJIMAN
|PHC EPENTI
|PHC NKO
CROSS RIVER	YALA	PHC OKUKU
|PHC WANOKOM
|PHC OKPOMA
|
DELTA	ANIOCHA NORTH 	IDUMUJE PHC
|UGBODU PHC
|ISSELE-AZAGBA PRIMARY HEALTH CARE CENTRE
|ISSELE-UKU GOODNEWS CLINIC
|ISSELE-UKU PRIMARY HEALTH CENTRE
|OBIOR PRIMARY HEALTH CENTRE
|IDUMUOGO PRIMARY HEALTH CARE CENTRE
|ONICHA OLONA GOVERNMENT HOSPITAL.
|ONICHA-UGBO PRIMARY HEALTH CENTRE
|UBULUBU PRIMARY HEALTH CENTRE
DELTA	ANIOCHA SOUTH 	ADONTE PRIMARY HEALTH CENTRE
|OGWASHI-UKU PRIMARY HEALTH CENTRE
|EGBUDU-AKAH PRIMARY HEALTH CENTRE
|ABAH-UNOR PRIMARY HEALTH CENTRE
|EWULU PRIMARY HEALTH CENTRE
|OLODU PRIMARY HEALTH CENTRE
|NSUKWA PRIMARY HEALTH CENTRE
|AZAGBA PRIMARY HEALTH CENTRE
|UBULU-OKITI PRIMARY HEALTH CENTRE
|UBULU_UKU GENERAL HOSPITAL
|ASHAMA PRIMARY HEALTH CENTRE
DELTA	BOMADI 	AKUGBENE PRIMARY HEALTH CENTRE
|BOMADI PRIMARY HEALTH CENTRE
|EKAMETAGBENE PRIMARY HEALTH CENTRE
|KALAFIOGBENE PRIMARY HEALTH CENTRE
|ESANMA PRIMARY HEALTH CENTRE
|KPAKIAMA PRIMARY HEALTH CENTRE
|EZEBIRI PRIMARY HEALTH CENTRE
|OGRIAGBENE PRIMARY HEALTH CENTRE
|OGBEINAMA PRIMARY HEALTH CENTRE
DELTA	BURUTU 	BULOU-NDORO PRIMARY HEALTH CENTRE
|EGODOR PRIMARY HEALTH CENTER
|OBORO PRIMARY HEALTH CARE CENTER
|OKPOKUNOU PRIMARY HEALTH CARE CENTER
|BIKOROGHA PRIMARY HEALTH CARE CENTER
|KIAGBODO PRIMARY HEALTH CARE CENTER
|OBOTEBE PRIMARY HEALTH CENTRE
|ODIMODI PRIMARY HEALTH CENTRE
|TAMIGBE PRIMARY HEALTH CARE CENTER
|OGBOBAGBENE PRIMARY HEALTH CENTRE
DELTA	ETHIOPE EAST 	ABRAKA PRIMARY HEALTH CENTRE
|KOKORI INLAND PRIMARY HEALTH CENTRE
|DELSUTH ABRAKA
|ISIOKOLO PRIMARY HEALTH CENTRE
|OKUREKPO PRIMARY HEALTH CENTRE
|ORHOAKPO HEALTH CENTRE
|ORIA-ABRAKA PRIMARY HEALTH CENTRE
|OVU PRIMARY HEALTH CENTRE
|OKPARA WATER SIDE PHC
DELTA	ETHIOPE WEST 	EJENESA PRIMARY HEALTH CENTRE
|EKRODA PRIMARY HEALTH CARE CENTRE
|UGBOMOYA WATER- SIPRIMARY HEALTH CARE
|BOBOROKU PRIMARY HEALTH CENTRE
|MOSOGAR TOWN PRIMARY HEALTH CENTRE
|UGBOKPA PRIMARY HEALTH CENTER
|IJOMI PRIMARY HEALTH CENTRE
|OGHAREFE PRIMARY HEALTH CENTRE
|OVA PRIMARY HEALTH CENTRE
|OGHAREKI PRIMARY HEALTH CENTRE
|OGHAREKI MODEL PRIMARY HEALTH CENTRE
DELTA	IKA NORTH EAST 	AKWUMAZI PRIMARY HEALTH CENTRE
|IDUMUESAH PRIMARY HEALTH CARE CENTRE
|IGBODO PRIMARY HEALTH CENTRE
|LGA SECRETARIAT
|BOJI-BOJI OWA PHC
|OWA-ALERO GOVERNMENT HOSPITAL
|OWA-ALERO PRIMARY HEALTH CARE CENTRE
|OWA-ALIZOMOR PRIMARY HEALTH CENTRE
|OWANTA PRIMARY HEALTH CARE CENTRE
|OWA-ALIDINMA PRIMARY HEALTH CARE CENTRE
|UMUNEDE PRIMARY HEALTH CARE CENTRE
|UTE-OGBEJE PRIMARY HEALTH CENTRE
|UTE-OKPU PRIMARY HEALTH CARE CENTRE
DELTA	IKA SOUTH 	ABAVO CENTRAL PRIMARY HEALTH CENTRE
|AGBOR-NTA PRIMARY HEALTH CENTRE
|AGBOR-OBI PRIMARY HEALTH CENTRE
|ALIAGWE PRIMARY HEALTH CENTRE
|AGBOR MODEL PRIMARY HEALTH CENTRE
|EKUKU-AGBOR PRIMARY HEALTH CENTRE
|EMUHU PRIMARY HEALTH CENTRE
|MPHCC
|ALISIMIE PRIMARY HEALTH CENTRE
|CENTRAL HOSPITAL 
DELTA	ISOKO NORTH 	ARADHE PRIMARY HEALTH CARE CENTRE
|EMEVOR PRIMARY HEALTH CENTRE
|ISI EMEVOR PRIMARY HEALTH CENTRE
|IWRIDE-IYE PRIMARY HEALTH CENTRE
|EKIUGBO IYE PRIMARY HEALTH CENTRE
|OFAGBE PRIMARY HEALTH CENTRE
|OKPE ISOKO PRIMARY HEALTH CENTRE
|OWHELOGBO PRIMARY HEALTH CENTRE
|AKIEWHE PRIMARY HEALTH CENTRE
|OTIBIO OWHE PRIMARY HEALTH CENTRE
|BETHEL PRIMARY HEALTH CENTRE
|EROVIE PRIMARY HEALTH CENTRE
|OZORO PRIMARY HEALTH CENTRE
DELTA	ISOKO SOUTH 	IRRI PHC
|EME PRIMARY HEALTH CENTRE
|ENHWE PRIMARY HEALTH CENTRE
|EGBO-IGBI PRIMARY HEALTH CENTRE
|IDHEZE PRIMARY HEALTH CENTRE
|OLEH PRIMARY HEALTH CENTRE
|MARY/MARTHA  HOSPITAL
|OLOMORO PRIMARY HEALTH CENTRE
|UMEH PRIMARY HEALTH CENTRE
|UZERE PRIMARY HEALTH CENTRE
DELTA	NDOKWA EAST	ABOH PHC
|OKPAI PHC
|ASABA-ASE PRIMARY HEALTH CARE CENTRE
|ASE PRIMARY HEALTH CENTRE
|ASHAKA PRIMARY HEALTH CENTRE
|EKPE PRIMARY HEALTH CENTRE
|BENEKU PRIMARY HEALTH CARE CENTRE
|IBREDE PRIMARY HEALTH CENTRE
|ABALLA-OBODO HEALTH CLINIC
|UMUOLU PRIMARY HEALTH CENTRE
|OLOA OSSISSA PRIMARY HEALTH CENTRE
DELTA	NDOKWA WEST	UMUSAM PHC
|EMU-EBENDO PRIMARY HEALTH CARE CENTRE
|ETUA PRIMARY HEALTH CARE CENTRE
|TABOWEI MEDICAL CENTRE
|URBAN PRIMARY HEALTH CARE CENTER
|NDEMILI PRIMARY HEALTH CARE CENTRE
|UTUE-OGUME PRIMARY HEALTH CARE CENTRE
|OGBE-OLE PRIMARY HEALTH CARE CENTRE
|ONICHA UKWANI PRIMARY HEALTH CARE CENTRE
|UTAGBA UNO PRIMARY HEALTH CARE CENTRE
DELTA	OKPE 	ADAGBRASSA PRIMARY HEALTH CARE CENTER
|ADEJE PRIMARY HEALTH CENTRE
|AGHALOPKE PRIMARY HEALTH CENTRE
|AMOUKPOKPO PRIMARY HEALTH CENTRE
|UGHOTON PRIMARY HEALTH CENTRE
|OHA PRIMARY HEALTH CARE CENTRE
|OSUBI PRIMARY HEALTH CARE CENTRE
|MEREJE GOVENMENT HOSPITAL
|OKUABU PRIMARY HEALTH CENTRE
|OREROKPE PRIMARY HEALTH CARE CENTRE
|OVIRI OKPE PRIMARY HEALTH CARE CENTRE
DELTA	OSHIMILI NORTH 	ACHALA IBUSA PRIMARY HEALTH CENTRE
|AKWUKWU-IGBO GOVERNMENT HOSPITAL
|ATUMA PRIMARY HEALTH CENTRE
|EBU PRIMARY HEALTH CENTRE
|ILLAH PRIMARY HEALTH CENTRE
|OKPANAM PRIMARY HEALTH CENTRE
|UGBOLU PRIMARY HEALTH CENTRE
|UKALLA OKPUNOR PRIMARY HEALTH CENTRE
|IBUSA PRIMARY HEALTH CENTRE
DELTA	OSHIMILI SOUTH 	AKWUEBULU PRIMARY HEALTH CENTRE
|CABLE POINT ASABA PRIMARY HEALTH CENTRE
|FEDERAL MEDICAL CENTER
|POLICE CLINIC
|OKWE PRIMARY HEALTH CENTRE
|UMUAGU ASABA PRIMARY HEALTH CENTRE
|ANWAI PRIMARY HEALTH CENTRE
DELTA	PATANI 	TORU-ANGIANA PHC
|AGOLOMA PRIMARY HEALTH CENTRE
|BULU-APELEBIRI PRIMARY HEALTH CENTRE
|ODORUBU PRIMARY HEALTH CENTRE
|PATANI PRIMARY HEALTH CENTRE
|UDUOPHORI PRIMARY HEALTH CENTRE
DELTA	SAPELE 	AMUKPE PRIMARY HEALTH CENTRE
|ADAGBRASSA PRIMARY HEALTH CENTRE 
|ETA-AMUA PRIMARY HEALTH CENTRE
|GANA PRIMARY HEALTH CENTRE
|UGBORHEN PRIMARY HEALTH CENTRE
DELTA	UDU 	ALADJA PRIMARY HEALTH CENTRE
|EGINI PRIMARY HEALTH CARE CENTRE
|EMADADJA PRIMARY HEALTH CARE CENTRE
|OGBE-UDU PRIMARY HEALTH CENTRE
|OKETE PRIMARY HEALTH CARE CENTRE
|ORHUWHORUN PRIMARY HEALTH CARE CENTRE
|OTOR-UDU PRIMARY HEALTH CARE CENTRE
|OWHRO PRIMARY HEALTH CENTRE
DELTA	UGHELLI NORTH	UFUOMA HEALTH CENTER
|AGBARHA-OTOR PRIMARY HEALTH CENTRE
|OMOVWODORIRHIBO PRIMARY HEALTH CENTRE
|AGBARHO  PRIMARY HEALTH CENTRE
|EKRERHAVWE PRIMARY HEALTH CENTRE
|CENTRAL HOSPITAL AGBARU
|ERHOBARO PRIMARY HEALTH CENTRE
|OROGUN GOVERNMENT HOSPITAL
|EKIUGBO PHC
|URBAN PRIMARY HEALTH CENTRE
|UWHERU PRIMARY HEALTH CENTRE
DELTA	UGHELLI SOUTH 	EDJOPHE PRIMARY HEALTH CENTRE
|EKAKPAME PRIMARY HEALTH CENTRE
|USIEFRU PRIMARY HEALTH CENTRE
|EWU PRIMARY HEALTH CENTRE
|FRUKAMA HEALTH POST
|OLOTA  PRIMARY HEALTH  CENTRE
|UGHEVWUGHE PRIMARY HEALTH CENTRE
|OTU-JEREMI PRIMARY HEALTH CENTRE
|OKWAGBE PRIMARY HEALTH CENTRE
|EGBO-IDEH PRIMARY HEALTH CENTRE
|OTORERE-OLOMU PRIMARY HEALTH CENTRE
|OVIRI-OLOMU PRIMARY HEALTH CENTRE
|UMUAJA PHC
|AMAI  ISHIKAGUMA PRIMARY HEALTH CARE CENTER
|ADONISHAKA PRIMARY HEALTH CARE CENTER
|EZIOKPOR PRIMARY HEALTH CARE CENTER
|URBAN PRIMARY HEALTH CENTRE
|KEM NURSING AND MATERNITY HOME
|UMUEBU PRIMARY HEALTH CARE CENTER
|OWA-ABBI PRIMARY HEALTH CARE CENTER
|UMUTU PRIMARY HEALTH CARE CENTER
DELTA	UVWIE 	ALAKA PRIMARY HEALTH CENTRE
|EKPAN GENERAL HOSPITAL
|EKPAN 2 PRIMARY HEALTH CENTRE
|ENERHEN 1 PRIMARY HEALTH CENTRE
|ENERHEN 2 PRIMARY HEALTH CENTRE
|OHORHE PRIMARY HEALTH CENTRE
|UGBOMRO PRIMARY HEALTH CENTRE
|UGBOROKE COMPREHENSIVE PRIMARY HEALTH CENTRE
|UGBORIKOKO PRIMARY HEALTH CENTRE
DELTA	WARRI NORTH 	KOKO PRIMARY HEALTH CENTRE
DELTA	WARRI SOUTH 	EDJEBA HEALTH POST
|EKUREURHOBO PRIMARY HEALTH CARE
|OGUNU PRIMARY HEALTH CARE
|IGBUDU PRIMARY HEALTH CARE
|UKPOKITI PRIMARY HEALTH CENTRE
|ODE-ITSEKIRI  HEALTH FACILITY
|PESSU PRIMARY HEALTH CARE
|URBAN PHC
|UBEJI PRIMARY HEALTH  CARE
|AJAMIMOGHA PRIMARY HEALTH CENTRE
DELTA	WARRI SOUTH WEST 	AJUDIABO PRIMARY HEALTH CENTRE
|MADAGHO PRIMARY HEALTH CENTRE
|AKPAKPA PHC
|OGIDIGBEN PRIMARY HEALTH CENTRE
|OGBE-IJOH PRIMARY HEALTH CENTRE
|OPOROZA PRIMARY HEALTH CENTRE
|UGBORODO PHC
|
 EBONYI	ABAKILIKI	AZUIYIOKWU MCH
|NEW TIMBER SHADE
 EBONYI	AFIKPO NORTH	AMAECHERA HC
|GH ITIM UKWU
|MDG AMATA AKPOHA
 EBONYI	 AFIKPO SOUTH	GH OWUTU
|NGUZU HC
 EBONYI	EBONYI	OGUZORONWEYA HC
|NSUGBE MCH
 EBONYI	EZZA NORTH	UMUEZEKOHA GH
|EKKA HC
 EBONYI	EZZA SOUTH	ONUEKE GH
|OKOFFIA AZUEBONYI HC
 EBONYI	IKWO	ABANI MDG
|OBEAGUELEKE HC
 EBONYI	ISHIELU	AGBA GH
|NDIAGU UMUEZEOKE HP
 EBONYI	IVO	ISHIAGU BASIC HC
|AKAEZE UKWU HP
 EBONYI	IZZI	IBOKO GH
|NDIEBOYISHIAGU HC
|IZIOGO HC
 EBONYI	OHAOZARA	OKPOSI GH
|UGWULANGWU HC
|OBIOZARA HC
 EBONYI	OHAUKWU	EZZANGBO GH
|NGBO MATERNITY
 EBONYI	ONICHA	ONICHA HC
|ISU HC
|
EDO	AKOKO-EDO	IBILO GEN HOSP
|OSSOSO YOLA PHC
|ENWAN PRIMARY HEALTH CENTRE
|BENIN PSYCHIATRIC HOSPITAL
EDO	EGOR 	UNIVERSITY OF BENIN TEACHING HOSPITAL
|USEH PRIMARY HEALTH CENTRE
|EGUA-EDAIKEN COMPREHENSIVE HEALTH CENTRE
|UWELU PRIMARY HEALTH CENTRE
EDO	ESAN CENTRAL LOCAL GOVERNMENT AREA	OPOJI PRIMARY HEALTH CENTRE
|EGUARE IRRUA MODEL PRIMARY HEALTH CENTRE
| IRRUA SPECIALIST TEACHING HOSPITAL
|UGBEGUN PRIMARY HEALTH CENTRE
|EFANDION  PRIMARY HEALTH CENTRE
EDO	ESAN NORTH-EAST 	CENTRAL HOSPITAL UROMI
|UROMI URBAN HEALTH CENTRE
|OBEIDU PRIMARY HEALTH CENTRE
|OBIYON PRIMARY HEALTH CENTRE
|GENERAL HOSPITAL EWOHIMI
EDO	ESAN SOUTH-EAST 	ILLISHI PRIMARY HEALTH CENTRE
|UBIAJA PRIMARY HEALTH CENTRE
|GENERAL HOSPITAL UBIAJA
|UGBOHA COMPREHENSIVE HEALTH CENTRE
|GENERAL HOSPITAL EKPOMA
EDO	ESAN WEST 	ESEOHE MEDICAL CENTRE
|IHUMUDUMU PRIMARY HEALTH CENTRE
|GENERAL HOSPITAL IRUEKPEN
|OGWA COMPREHENSIVE HEALTH CARE CENTRE
|FUGAR GENERAL HOSPITAL
EDO	ETSAKO CENTRAL 	IVINONE COMPREHENSIVE PRIMARY HEALTH CENTRE
|OSOMEGBE PRIMARY HEALTH CENTRE
|UDOCHI PRIMARY HEALTH CENTRE
|UGBEKPE COMPREHENSIVE HEALTH CENTRE
|AFOKPELLA PRIMARY HEALTH CENTRE
EDO	ETSAKO EAST 	AGENEBODE GENERAL HOSPITAL
|IVIANOKPODI PRIMARY HEALTH CENTRE
|OKUGBE COMPREHENSIVE HEALTH CENTRE
|OKPEKPE PRIMARY HEALTH CENTRE
|CENTRAL HOSPITAL AUCHI
EDO	ETSAKO WEST 	AUCHI PRIMARY HEALTH CENTRE
|IYAMOH COMPREHENSIVE HEALTH CENTRE
|AYOGWIRI PRIMARY HEALTH CENTRE
|JATTU PRIMARY HEALTH CENTRE
|AFUDA PRIMARY HEALTH CENTRE
EDO	IGUEBEN 	EBELLE PRIMARY HEALTH CENTRE
EDO	IGUEBEN 	GENERAL HOSPITAL IGUEBEN
|EWOSSA PRIMARY HEALTH CENTRE
|UDO EGUARE  PRIMARY HEAITH CENTER
|EVBOMODU PRIMARY HEALTH CENTRE
|OGHEGHE PRIMARY HEALTH CENTRE
|OGBESON PRIMARY HEALTH CENTRE
|OLOGBO PRIMARY HEALTH CENTRE
|UGBEKUN PRIMARY HEALTH CENTRE
|IWOGBAN PRIMARY HEALTH CENTRE
EDO	IKPOBA-OKHA 	ARUOGBA PRIMARY HEALTH CENTRE
EDO	OREDO 	CENTRAL HOSPITAL BENIN CITY
|OREDO PRIMARY HEALTH CENTRE
|STELLA OBASANJO WOMEN AND CHILDREN HOSPITAL
|NEW BENIN PHC
|GENERAL HOSPITAL ABUDU
EDO	ORHIONMWON 	IGBANKE GENERAL HOSPITAL
|GOVERNMENT HOSPITAL URHONIGBE
|EKIADOLOR PRIMARY HEALTH CENTRE
EDO	OVIA NORTH-EAST 	ODUNA PRIMARY HEALTH CENTRE
|IGBINEDION UNIVERSITY TEACHING HOSPITAL
|OKADA PRIMARY HEALTH CENTRE
|OLUKU PRIMARY HEALTH CENTRE
|IGUOBAZUWA GENERAL HOSPITAL
EDO	OVIA SOUTH-WEST 	ORA COMPREHENSIVE HEALTH CENTRE
|SILUKO PRIMARY HEALTH CENTRE
|UDO COMPREHENSIVE HEALTH CENTRE
|OFUNMWENGBE PRIMARY HEALTH CENTRE
|AFUZE GENERAL HOSPITAL
EDO	OWAN EAST 	AFUZE REFERRAL CENTRE
|IHIEVBE-OGBE PRIMARY HEALTH CENTRE
|OLUMA PRIMARY HEALTH CENTRE
|AMOYA PRIMARY HEALTH CENTRE
|GENERAL HOSPITAL SABON GIDA ORA
|MICHEAL IMOUDU COMPREHENSIVE HEALTH CENTRE
|SOBE 1 PRIMARY HEALTH CENTRE
|UHONMORA PRIMARY HEALTH CENTRE
|UZEBBA GENERAL HOSPITAL
|EHOR PRIMARY HEALTH CENTRE
EDO	UHUNMWONDE 	IGIEDUMA PRIMARY HEALTH CLINIC
|IKHUENIRO PRIMARY HEALTH CENTRE
|EGBA, EGBA DISTRICT HOSPITAL
|EYEAN PRIMARY HEALTH CENTRE
|
EKITI	ADO	OKESA COMPREHENSIVE HEALTH CENTRE
|UNIVERSITY TEACHING HOSPITAL
|EKITI SECRETARIAT STAFF CLINIC
|AGO ADOLUJU BASIC HEALTH CLINIC
|BASIRI BASIC HEALTH CLINIC
|PRISON HEALTH CLINIC
|IRONA BASIC HEALTH CLINIC
|BASIC HEALTH CENTRE FEDERAL HOUSING
|MOFERERE BASIC HEALTH CLINIC
|ODO ADO BASIC HEALTH CLINIC
|ODO BASIC HEALTH CLINIC
|IDOLOFIN BASIC HEALTH CLINIC
|ADO FAMILY SUPPORT PROGRAMME CLINIC
|IGIRIGIRI BASIC HEALTH CLINIC
|OBADEJUGBE GENERAL HOSPITAL
|OPOPOGBORO BASIC HEALTH CLINIC
|OKE ILA BASIC HEALTH CLINIC
EKITI	AIYEKIRE (GBONYIN)	ODE COMPREHENSIVE HEALTH CENTRE
|IJAN GENERAL HOSPITAL
|AISEGBA BASIC HEALTH CENTER
|IMESI COMPREHENSIVE HEALTH CENTRE
EKITI	EFON	EREKESAN HEALTH CENTRE
|ALAJO BASIC HEALTH CENTRE
EKITI	EKITI EAST	KOTA EKITI ARAROMI COMPREHENSIVE HEALTH CENTRE
|ISINBODE BASIC HEALTH CENTRE
|ILASA BASIC HEALTH CENTRE
|OMUO OKE COMPREHENSIVE HEALTH CENTRE
EKITI	EKITI SOUTH WEST	ILAWE COMPREHENSIVE HEALTH CENTRE
|IGBARA ODO COMPREHENSIVE HEALTH CENTRE
|OGOTUN BASIC HEALTH CENTRE
|ILAWE EKITI GENERAL HOSPITAL
EKITI	EKITI WEST	ERINYIYAN COMPREHENSIVE HEALTH CENTRE
|OKEMESI BASIC HEALTH CENTRE
|CHC ARAMOKO
|ARAMOKO GENERAL HOSPITAL
|IDO ILE COMPREHENSIVE HEALTH CENTRE
EKITI	EMURE	EMURE COMPREHENSIVE HEALTH CENTRE
|EPORO MATERNITY CENTRE
EKITI	IDO-OSI	IDO FEDERAL MEDICAL CENTRE
|IFAKI COMPREHENSIVE HEALTH CENTRE
|AYETORO COMPREHENSIVE HEALTH CENTRE
EKITI	IJERO	ODOESE HEALTH CENTRE
|IKORO COMP HEALTH CENTRE
|AYEGUNLE BASIC HEALTH CENTRE
|IPOTI COMPREHENSIVE HEALTH CENTRE
|IROKO BASIC HEALTH CENTRE
EKITI	IKERE	CHC AFAO
|IKERE STATE SPECIALIST HOSPITAL
|IKERE COLLEGE OF EDUCATION HEALTH CENTRE
|ATIBA BASIC HEALTH CENTER
EKITI	IKOLE	METHODIST COMPREHENSIVE HEALTH CENTER IKOLE
|ARA BASIC HEALTH CENTRE
|ODO ORO BASIC HEALTH CENTRE
|AYEDUN COMPREHENSIVE HEALTH CENTRE
EKITI	ILEJEMEJE	EDA ONIYO COMPREHENSIVE HEALTH CENTRE
|IYE COMPREHENSIVE HEALTH CENTRE
EKITI	IREPODUN/ IFELODUN	IGEDE COMPREHENSIVE HEALTH CENTRE
|IWOROKO HEALTH CENTRE
|IGBEMO COMPREHENSIVE HEALTH CENTRE
|IYIN GENERAL HOSPITAL
EKITI	ISE/ORUN	OKEYARD COMPREHENSIVE HEALTH CENTRE
|AJEGUNLE BASIC HEALTH CENTRE
|OBADA BASIC HEALTH CENTRE
EKITI	MOBA	OTUN COMPREHENSIVE HEALTH CENTRE
|IGOGO COMPREHENSIVE HEALTH CENTRE
|OSUN BASIC HEALTH CENTRE
EKITI	OYE	OYE COMPREHENSIVE HEALTH CENTRE
|IRE BASIC HEALTH CENTRE
|ISAN BASIC HEALTH CENTRE
|ITAPA BASIC HEALTH CENTRE
|OYE GENERAL HOSPITAL
|
ENUGU	ANINRI	NDEABOH HEALTH CENTRE
|OKPANKU HEALTH CENTER
ENUGU	AWGU	MCH AWGU
|IHE HEALTH CENTRE
ENUGU	ENUGU EAST	ABAKPA HEALTH CENTRE
|NATIONAL ORTHOPAEDIC HOSPITAL, ENUGU
|IBAGWA-NIKE HEALTH CENTRE
ENUGU	ENUGU NORTH	NEW HEAVEN HEALTH CENTRE
|OGUI NIKE HEALTH CENTRE
|ESUT PARKLANE 
|ASATA HEALTH CENTRE
ENUGU	ENUGU SOUTH	UWANI HEALTH CENTRE
|AMECHI COTTAGE HOSPITAL
ENUGU	EZEAGU	AGUOBUOWA HEALTH CENTRE
|AKAMA HEALTH CENTER
ENUGU	IGBO-ETITI	OGBEDE HEALTH CENTRE
|ACHARA OHODO HEALTH CENTRE
ENUGU	IGBO-EZE NORTH	OGURUTE HEALTH CENTRE
|UDA HEALTH CENTRE
|ENUGU EZIKE GENERAL HOSPITAL
ENUGU	IGBO-EZE SOUTH	IBAGWA HEALTH CENTRE
|ITCHI UWENU HEALTH CENTRE
ENUGU	ISI UZO	IKEM HEALTH CENTRE
|AMEDE HEALTH CENTRE
ENUGU	NKANU EAST	NARA 1 HEALTH CENTRE
|OWO HEALTH CENTRE
ENUGU	NKANU WEST	UNTH ITUKU OZALLA
|AGBANI HEALTH CENTER
|OZALLA HEALTH CENTRE
ENUGU	NSUKKA	NSUKKA HEALTH CENTRE
|ELUAGU OBUKPA HEALTH CENTRE
|OPI HEALTH CENTRE
ENUGU	OJI RIVER	BASIC HEALTH CARE CENTRE, UGWUOBA
|INYI HEALTH CENTRE
ENUGU	UDENU	OBOLLO AFOR HEALTH CENTRE
|MODEL PHC, ORBA
ENUGU	UDI	UMUAKA NSUDE HEALTH CENTRE
|EKE HEALTH CENTRE
|UDI GENERAL HOSPITAL
ENUGU	UZO UWANI	ADANI HEALTH CENTRE
|
FCT	ABAJI	MAWOGI PHC CENTER
|ABAJI NEW TOWNSHIP PHC CENTER
|EBAGI PHC CENTER
|GAWU PHC Center
|GURDI PHC CENTER
|ABAJI GENERAL HOSPITAL
|AYAURA  PHC center
|NUKU PHC CENTER
|AGYANA PHC CENTER
|NAHARATI PHC CENTER
|YABA PHC Center
FCT	BWARI	BWARI GENERAL HOSPITAL
| GABA PHC Center
|IGU PHC Center
|DUTSE ALHAJI PHC Center
|MPAPE PHC Center
|DUTSE MAKARANTA PHC Center
|USHAFA PHC Center
|DEI DEI PHC CENTER
|KUBWA GENERAL HOSPITAL
|BWARI TOWN PHC Center
|SHERE PHC CENTER
|BYAZHIN PHC CENTER
|KOGO PHC Center
|BYAZHIN PHC CLINIC
|USUMA PHC CLINIC
|KUDURU PHC CLINIC
|KAWU PHC CLINIC
|DUTSE PHC CLINIC
|DUTSE PHC CLINIC
|KUBWA PHC CENTER
FCT	GWAGWALADA	DAGIRI PHC Center
|DOBI PHC Center
|GWAKO PHC Center
|ARMY BARRACKS CLINIC
|IBWA 1 PHC Center
|YIMI PHC CENTER
|PHC Center Angwa Geshi ( TOWN SHIP CLINIC)
|OLD KUTUNKU PHC Center
|PAIKO PHC CENTER
|GLADA TEACHING HOSPITAL
|TUGAN MAJE PHC Center
|ZUBA PHC Center
|PHASE 3 PHC CENTER
|QUARTERS
|CENTRAL 
|ZUBA 1
|ZUBA 2
FCT	KUJE	KUJE GENERAL HOSPITAL
|KUJE PHC Center
|CHIBIRI PHC CENTER
|CHUKUKU PHC CENTER
|GAUBE PHC Center
|PEGI PHC Center
|KABI KASA PHC CENTER
|AGWAI PHC CENTER
|KWAKU PHC Center
|RUBOCHI GENERAL HOSPITAL
|GUDUN KARYA PHC Center
|KUCHIYAKO PHC CENTER
|RUBOCHI PHC Center
|KIYI PHC CENTER
|LANTO PHC CENTER
|ABUJA @ 30 PHC CENTER
|KABI MONGORO PHC CENTER
|GWARGWADA PHC CENTER
|KULO PHC CENTER
|ZAGABUTU PHC CENTER
|KUJEKWA PHC CENTER
|YENCHE PHC CENTER
|SABO PHC CENTER
|GOMO PALACE
FCT	KWALI	ASHARA PHC CENTER
|DAFA PHC Center
|KWAITA HAUSA PHC CENTER
|DABI /BAKO PHC Center
|KWALI GEN, HOSPITAL
|KILANKWA 1  PHC Center
|WAKO PHC Center
|KUNDU PHC CENTER
|YANGOJI PHC CENTER
|KWAITA PHC CENTER
FCT	AMAC	NATIONAL HOSPITAL SITE 1
|NATIONAL HOSPITAL SITE 2
|NATIONAL HOSPITAL SITE 3
|NATIONAL HOSPITAL SITE 4
|ASOKORO HOSPITAL
|PHC Clinic (FAMILY HEALTH CLINIC) Garki Area 3
|MOGADISHU HOSPITAL
|STATE HOUSE CLINIC SITE 1
|STATE HOUSE CLINIC SITE 2
|STATE HOUSE CLINIC SITE 3
|NATIONAL ASSEMBLY CLINIC SITE 1
|NATIONAL ASSEMBLY CLINIC SITE 2
|NATIONAL ASSEMBLY CLINIC SITE 3
|NATIONAL ASSEMBLY CLINIC SITE 4
|CBN CLINIC
|POLICE CLINICS
|APO PHC Center
|KOBI PHC CENTER
|063 NAF BASE HOSPITAL
|TUNGAN MADAKI PHC CENTER
|GOSSA PHC CENTER
|KAGINI PHC Center
|Dei-Dei PHC CENTER
|KUCHI GORO PHC Center
|FEDERAL MEDICAL CENTER JABI SITE 1
|FEDERAL MEDICAL CENTER JABI SITE 2
|FEDERAL MEDICAL CENTER JABI SITE 3
|GWARINPA GEN, HOSPITAL
|FED, ROAD SAFETY CLINIC
|GISHIRI PHC CENTER
|GWARINPA PHC CENTER
|JIWA PHC Center
|BASSAN JIWA PHC CENTER
|LUGBE PHC Center
|KABUSA PHC Center
|ALEYITA PHC CENTER
|KETTI PHC CENTER
|KARSHI GEN, HOSPITAL
|KUSEKI PHC CENTER
|CUSTOM STAFF CLINIC 
|JIKWOYI PHC CENTER
|NYANYA GEN. HOSPITAL
|MUNAPE PHC CENTER
|GBAGALAPE PHC CENTER
|GIDAN MANGORO PHC Center
|OROZO PHC Center
|GUGUGU PHC CENTER
|MAITAMA DISTRICT HOSPITAL
|WUSE GEN, HOSPITAL
|JAHI PHC CENTER
|FAMILY HEALTH PHC CENTER
|FAMILY HEALTH PHC CENTER
|FAMILY HEALTH PHC CENTER
|POLICE CLINIC AREA 1
|ASOKORO HOSPITAL MOBILE TEAM
|APO PHC CENTER
|APO PHC CENTER
|KOBI PHC CLINIC
|GUI PHC CLINIC 
|GUI PHC CLINIC 
|GWAGWA PHC CENTER
|GWAGWA PHC CENTER
|KUCHINGORO PHC CLINIC
|GWARINPA PHC CLINIC
|GISHIRII PHC CLINIC
|KUCHINGORO PHC CLINIC
|KUCHINGORO PHC CLINIC
|JIWA PHC CLINIC
|BASSAN JIWA PHC CLINIC
|ALEITA PHC CLINIC
|ALEITA PHC CLINIC
|ALEITA PHC CLINIC
|KARSHI GENERAL HOSPITAL 
|KARSHI GENERAL HOSPITAL 
|KARU PHC CENTER
|JIKWOYI PHC CENTER
|MUNAPE PHC CLINIC
|MUNAPE PHC CLINIC
|GUGUGU PHC CENTER
|GUGUGU PHC CENTER
|WUSE GEN, HOSPITAL
|WUSE GEN, HOSPITAL
|JAHYI PHC CLINIC
|JAHYI PHC CLINIC
|FAMILY HEALTH PHC CENTER
|FAMILY HEALTH PHC CENTER
|GWARINPA GENERAL HOSPITAL
|GWARINPA GENERAL HOSPITAL
|WUSE GEN, HOSPITAL
|KABUSA  PHC CENTER
|ASOKORO GENERAL HOSPITAL
|ASOKORO GENERAL HOSPITAL
|WUSE GEN, HOSPITAL
|APO PHC CENTER
|GWARINPA GENERAL HOSPITAL
|MAITAMA DISTRICT HOSPITAL
|MAITAMA DISTRICT HOSPITAL
|NATIONAL HOSPITAL
|NATIONAL HOSPITAL
|
GOMBE	GOMBE	FEDERAL TEACHING HOSPITAL GOMBE
|STATE SPECIALIST HOSPITAL GOMBE
|PHC PANTAMI
|PHC MADAKI
|PHC TUDUN WADA
|PHC TOWN
|PHC KUMBIYA KUMBIYA
|PHCC NASARAWO
|PHC  KAGARAWAL
GOMBE	BALANGA	PHC DADIYA
|PHC TALASSE
|PHC PUTOKI
|PHC GELENGU
|PHC CHAM
GOMBE	AKKO	PHC KUMO 
|PHC GADAWO 
|MODEL PHC BOGO
|PHC TUMU
|PHC AKKO
|PHC PINDIGA
|PHC KALSHINGI
GOMBE	KWAMI	PHC MALAM SIDI
|PHC DABAN FULANI
|PHC ABUJA
|PHC DIRRI
GOMBE	KALTUNGO	AREA HEALTH OFFICE KALTUNGO 
|PHC KALARING
|PHC LAKIDIR
|PHC BAULE GARI
GOMBE	BILLIRI	PHC SABON LAYI
|PHC SANSANI
|PHC KEKKEL 
|PHC KULGUL
GOMBE	SHONGOM	PHC FILIYA 
|PHC LAPAN
|MPHC BOH
|PHC BURAK 
GOMBE	FUNAKAYE	PHC JALINGO
|PHC BAGE
|GENERAL HOSPITAL BAJOGA
|PHC SANGARU
|PHC TONGO
GOMBE	NAFADA	PHC BARWO NASARAWO
|PHC BIRIN FULANI
|PHC JIGAWA
|PHC NAFADA 
GOMBE	YAMALTU DEBA	PHC DEBA
|PHC LANO
|PHC KWADON
|MODEL PHC DADIN KOWA 
|PHC KURJALE
GOMBE	DUKKU	PHC DUKKU 
|PHC HASHIDU 
|PHC KUNDE
|PHC BOZONSHILWA
|
IMO	 ABOH-MBAISE LOCAL GOVERNMENT AREA	 ENYIOGUGU HEALTH CENTER
|GENERAL HOSPITAL ABOH MBAISE
| NKWOGWU HEALTH CENTRE
| NGURUNWEKE HEALTH CENTER
IMO	 AHIAZU-MBAISE LOCAL GOVERNMENT AREA	 NNARAMBIA HEALTH CENTRE
| UMUOKIRIKA PRARY HEALTH CENTER
IMO	 EHE-MBANO LOCAL GOVERNMENT AREA	UMUEZE I HEALTH CENTER
|UMUEZEALA OWERE HEALTH CENTER
IMO	 EZINIHITTE-MBAISE LOCAL GOVERNMENT AREA	 IFE/OWOTU PRARY HEALTH CENTRE
|OKPOFE HEALTH CENTER
IMO	 IDEATO NORTH LOCAL GOVERNMENT AREA	 ONICHA HEALTH CENTRE (EZINIHITTE)
| CHOKONEZE PRARY HEALTH CENTRE
| NDIAWA HEALTH CENTRE
| AKWU HEALTH CENTRE
| MARTERNAL AND CHILD HEALTHCARE URUALLA
IMO	 IDEATO SOUTH LOCAL GOVERNMENT AREA	 DIKENAFAI MATERNAL CHILD HEALTH CENTRE
| UMUDURU AHURUNWA PRARY HEALTH CENTRE
IMO	 IHITTE/UBOMA LOCAL GOVERNMENT AREA	 UMUAWUCHI HEALTH CENTRE
|ISINWEKE HEALTH CENTER
IMO	 IKEDURU LOCAL GOVERNMENT AREA	 AMAO HEALTH CENTRE
|IKEDURU GENERAL HOSPITAL
IMO	 ISIALA MBANO LOCAL GOVERNMENT AREA	 IHO BASIC HEALTH CENTRE
| OBOLLO HEALTH CENTRE
| OGBOR HEALTH CENTRE
| OSU PRIMARY HEALTH CENTRE
IMO	 ISU LOCAL GOVERNMENT AREA	 AMURIE OMANZE MATERNITY AND CHILD HEALTH CLINIC
IMO	 MBAITOLI LOCAL GOVERNMENT AREA	 UMUNNEATO HEALTH CENTRE, OGWA
| UBOMIRI MODEL PRARY HEALTH CENTRE
|NWAORIEUBI HEALTH CENTER
IMO	NGOR-OKPALA LOCAL GOVERNMENT AREA	 UMUNOHA HEALTH CENTRE
| ALULU PRARY HEALTH CENTRE
|UMUKABIA PHC
| UMUNEKE PRARY HEALTH CENTRE
| UMUOHIAGU PRARY HEALTH CENTRE
IMO	NJABA LOCAL GOVERNMENT AREA	 UMUAKA COMPREHENSIVE HEALTH CENTRE
| NNENASA HEALTH CENTRE
IMO	NKWERRE LOCAL GOVERNMENT AREA	 NKWERRE MATERNAL AND CHILD HEALTH CLINIC
| OWERRE NKWORJI COMPREHENSIVE HEALTH CENTRE
IMO	NWANGELE LOCAL GOVERNMENT AREA	 UMUKABIA MODEL PRARY HEALTH CENTRE
| UMUOZU COMPREHENSIVE HEALTH CENTRE
IMO	OBOWO LOCAL GOVERNMENT AREA	 OGBOTOUKWU HEALTH CENTER
| UMUARIAM PRARY HEALTH CENTRE
IMO	OGUTA LOCAL GOVERNMENT AREA	 EGBUOMA PRARY HEALTH CENTRE
| EZIORSU PRARY HEALTH CENTRE
IMO	OHAJI/EGBEMA LOCAL GOVERNMENT AREA	 OKWELLE HEALTH CENTRE
| OHUBA HEALTH CENTRE
IMO	OKIGWE LOCAL GOVERNMENT AREA	MGBIRICHI HEALTH CENTER
| ETIOHA HEALTH CENTRE
| AMURO PRARY HEALTH CENTER
IMO	ONUO LOCAL GOVERNMENT AREA	IHUBE PRARY HEALTH CENTER
| OKIGWE MATERNAL AND CHILD HEALTH CLINIC
IMO	ORLU LOCAL GOVERNMENT AREA	 UMUNA PRARY HEALTH CARE
| AMAIFEKE OFEAHIA MODEL PRARY HEALTH CENTER
| IHIOMA PRARY HEALTH CENTRE
|IMO STATE UNIVERSITY TEACHING HOSPITAL ORLU
IMO	ORSU LOCAL GOVERNMENT AREA	 EBENATOR HEALTH CENTRE
| IHITENANSA HEALTH CENTRE
IMO	ORU EAST LOCAL GOVERNMENT AREA	 UMUOKWE PRARY HEALTH CENTRE
|AWO GENERAL HOSPITAL
IMO	ORU WEST LOCAL GOVERNMENT AREA	 OMUMA MATERNAL AND CHILD HEALTH CENTER
| MGBIDI PRARY HEALTH CENTRE (MCH)
| NEMPI HEALTH CENTRE
IMO	OWERRI MUNICIPAL LOCAL GOVERNMENT AREA	 AREA M COMPREHENSIVE HEALTH CENTRE
|FEDERAL MEDICAL CENTRE OWERRI
|O STATE SPECIALIST HOSPITAL
|STAFF CLINIC OWERRI MUNICIPAL
IMO	OWERRI NORTH LOCAL GOVERNMENT AREA	 EGBU HEALTH CENTRE
| NAZE PRARY HEALTH CARE
| OWAELU  HEALTH CENTER
| IHEAGWA PRARY HEALTH CENTRE
IMO	 OWERRI WEST LOCAL GOVERNMENT AREA	 PRARY HEALTH CENTRE IRETTE
|UMUGUMA HEALTH CENTER
| NEKEDE-2 PRARY HEALTH CENTRE
| PRARY HEALTH CENTRE UMUGUMA
|
JIGAWA	AUYO	AUYAKAYI PRIMARY HEALTH CLINIC
|AUYO PRIMARY HEALTH CENTRE
|AYAMA PRIMARY HEALTH CLINIC
|AYAN PRIMARY HEALTH CLINIC
|KALGWAI PRIMARY HEALTH CENTRE
|GATAFA PRIMARY HEALTH CARE
|KAFUR PRIMARY HEALTH CLINIC
|TSIDIR HEALTH POST
|SHINGE PRIMARY HEALTH CLINIC
JIGAWA	BABURA	JARMAI PRIMARY HEALTH CLINIC
|BATALI PRIMARY  HEALTH CLINIC
|DORAWA HEALTH POST
|GARU PRIMARY HEALTH CLINIC
|GASAKOLI PRIMARY HEALTH CLINIC
|INSHARUWA PRIMARY HEALTH CLINIC
|JIGAWA BABURA MODEL PRIMARY HEALTH CENTRE
|KANYA PRIMARY HEALTH CENTRE (BABURA)
|KUZUNZUMI PRIMARY HEALTH CLINIC
|KYAMBO HEALTH POST
|MASKO PRIMARY HEALTH CLINIC
JIGAWA	BIRNIN KUDU	MAGAJIN GARI HEALTH POST
|KANGIRE HEALTH POST
|KANTOGA HEALTH POST
|BAMAINA PRIMARY HEALTH CENTRE
|KWANGWARA PRIMARY HEALTH CARE CLINIC
|TUKUDA PRIMARY HEALTH CARRE CLINIC
|SUNDIMINA PRIMARY HEALTH CARE  CLINIC
|BADINGU PRIMARY HEALTH CARE CENTRE
|UNGUWAR YA PRIMARY HEALTH CARE CLINIC
|WURNO PRIMARY HEALTH CARE CLINIC
|YALWAN DAMAI PRIMARY HEALTH CARE CLINIC
	BIRNIWA	KUKA-INKIWA HEALTH CLINIC
|BIRNIWA TASHIA HEALTH POST
|KUBUNA PRIMARY HEALTH CLINIC
|DIGINSA PRIMARY HEALTH CARE CENTER
|FAGI PRIMARY HEALTH CLINIC
|KACHALLARI PRIMARY HEALTH CLINIC
|KARANGA PRIMARY HEALTH CARE CENTER
|KAZURA PRIMARY HEALTH CARE CENTER
|KUPSA PRIMARY HEALTH CARE CENTER
|MATAMU PRIMARY HEALTH CLINIC
|NGUWA PRIMARY HEALTH CLINIC
JIGAWA	BUJI	AHOTO PRIMARY HEALTH CLINIC
|BUJI PRIMARY HEALTH CLINIC
|CHIRBUN HEALTH POST
|FALAGERI PRIMARY HEALTH CLINIC
|GANTSA PRIMARY HEALTH CENTRE
|KAWAYA PRIMARY HEALTH CLINIC
|KUKUMA PRIMARY HEALTH CLINIC
|LELAN KUDU PRIMARY HEALTH CLINIC
|MADABE HEALTH POST
|YAYARIN TUKUR HEALTH CLINIC
JIGAWA	DUTSE	ABAYA PRIMARY HEALTH CLINIC
|CHAMO PRIMARY HEALTH CLINIC
|DUNDUBUS PRIMARY HEALTH CLINIC
|DURU PRIMARY HEALTH CLINIC
|JAUDI PRIMARY HEALTH CLINIC
|KACHI HEALTH POST
|WURMA PRIMARY HEALTH CLINIC
|KUDAI PRIMARY HEALTH CLINIC
|YINA PRIMARY HEALTH CLINIC
|MADOBI PRIMARY HEALTH CLINIC
|SAKWAYA PRIMARY HEALTH CLINIC
	GAGARAWA	GAGARAWA GARI PRIMARY HEALTH CLINIC
|GAGARAWA PRIMARY HEALTH CENTRE
|GARIN CHIROMA HEALTH POST
|KORE BALATU PRIMARY HEALTH CLINIC
|MADAKA PRIMARY HEALTH CENTRE
|MAI'ADUWA PRIMARY HEALTH CLINIC
|MAIKILILI PRIMARY HEALTH CLINIC
|MEDU PRIMARY HEALTH CENTRE
|YALAWA PRIMARY HEALTH CLINIC
|ZARADA PRIMARY HEALTH CLINIC
	GARKI	BUDURU BASIC HEALTH CLINIC
|DOKO PRIMARY HEALTH CENTRE
|GARKI PRIMARY HEALTH CENTRE
|GWARZON GARKI PRIMARY  HEALTH CLINIC
|SUGUNGUN PRIMARY  HEALTH CLINIC
|KANYA PRIMARY HEALTH CLINIC
|KARGO BASIC HEALTH CLINIC
|KORE PRIMARY  HEALTH CLINIC
|MUKU PRIMARY  HEALTH CLINIC
|SAYORI PRIMARY HEALTH CLINIC
|DUHUWA GUMEL HEALTH POST
|BEKARYA PRIMARY  HEALTH CLINIC
|DAN AMA PRIMARY HEALTH CLINIC
|MAYANKAPRIMARY  HEALTH CLINIC
|DAURAWA BASIC HEALTH CLINIC
|GARIN GAMBO HEALTH CLINIC
|HAMMAYO HEALTH POST
|ZANGO PRIMARY HEALTH CLINIC
	GURI	ABUNABO PRIMARY HEALTH CLINIC
|ADIYANI PRIMARY HEALTH CLINIC
|DAWA HEALTH POST
|GARBAGAL HEALTH POST
|GURI PRIMARY HEALTH CENTER
|KADIRA HEALTH CLINIC
|LAFIYA HEALTH CLINIC
|MARGADU PRIMARY HEALTH CLINIC
|MUSARI PRIMARY HEALTH CLINIC
	GWARAM	BASIRKA PRIMARY HEALTH CENTRE
|RABADI PRIMARY HEALTH CARE CLINIC
|FAGAM PRIMARY HEALTH CENTER
|GALAMBI PRIMARY HEALTH CENTRE
|GWARAM COTTAGE HOSPITAL
|KILA HEALTH CLINIC
|KONDIKO PRIMARY  HEALTH CLINIC
|MARUTA PRIMARY  HEALTH CLINIC
|SARA PRIMARY HEALTH CLINIC
|TSANGARWA PRIMARY HEALTH CLINIC
|ZANDAM NAGOGO HEALTH POST
	GWIWA	BUNTUSU HEALTH POST
|DABI BASIC HEALTH CLINIC
|MARAGANTA  PRIMARY  HEALTH CLINIC
|FIRJIN YAMMA HEALTH POST
|INDIRAWA BASIC HEALTH CLINIC
|GWIWA PRIMARY HEALTH CENTRE
|KORAYEL  PRIMARY HEALTH  CLINIC
|RORAU PRIMARY HEALTH  CLINIC
|SHAFE PRIMARY HEALTH CLINIC
|YOLA PRIMARY HEALTH  CLINIC
|ZAUMA PRIMARY HEALTH CLINIC
JIGAWA	HADEJA	AGUMO PRIMARY HEALTH CENTRE
|KOFAR AREWA MATERNAL CLINIC (HADEJA)
|GAWUNA PRIMARY HEALTH CENTRE
|BADERIN GABAS PRIMARY HEALTH CENTRE
|GABARI PRIMARY HEALTH CENTRE
|FANTAI PRIMARY HEALTH CLINIC
	JAHUN	AUJARA PRIMARY HEALTH CENTRE
|KAOWAWA PRIMARY HEALTH CENTRE
|LAUTAI PRIMARY HEALTH CLINIC
|GUNKA PRIMARY HEALTH CLINIC
|HARBO SABUWA PRIMARY HEALTH CLINIC
|HARBO  PRIMARY HEALTH CLINIC
|IDANDUNA PRIMARY  HEALTH CLINIC
|JABARNA PRIMARY  HEALTH CLINIC
|JAHUN URBAN MATERNITY CLINIC
|KALE PRIMARY HEALTH CLINIC
|KANWA PRIMARY HEALTH CLINIC
	KAFIN HAUSA	TUMINJIRA HEALTH POST
|DUMADUMIN TOKA HEALTH CLINIC
|RAMFA BASIC HEALTH CLINIC
|JABO PRIMARY HEALTH CENTRE
|KANZAN HEALTH POST
|KWAZALEWA HEALTH POST
|SHAKATO BASIC HEALTH CLINIC
|KWATALO PRIMARY HEALTH CARE CENTRE
|RUBA PRIMARY HEALTH CLINIC
|SARAWA HEALTH POST
|SHAMAKERI HEALTH POST
	KAUGAMA	ARBUS PRIMARY HEALTH CLINIC
|UBBA HEALTH POST
|DABUWARAN  HEALTH CLINIC
|NUHU ALPHA PRIMARY HEALTH CENTRE
|GIRBOBO HEALTH CLINIC
|HADIN HEALTH POST
|JE'A HEALTH CLINIC
|KAUGAMA PRIMARY HEALTH CENTRE
|MARKE PRIMARY HEALTH CENTRE
|UNGUWAR JIBRIN HEALTH POST
|YALO BASIC HEALTH CLINIC
JIGAWA	KAZAURE	KAFIN CHIROMA BASIC HEALTH CLINIC
|FARUN DABA PRIMARY HEALTH CLINIC
|DUNGUYAWA BASIC HEALTH CLINIC
|DANDI BASIC HEALTH CLINIC
|GADA PRIMARY HEALTH CLINIC
|KATOGE HEALTH POST
|KARAFTAYI HEALTH CLINIC
|SABARU PRIMARY HEALTH CLINIC
|UNGUWAN YAMMA  PRIMARY HEALTH CLINIC
	KIRI KASSAMA	BATURIYA BASIC HEALTH CLINIC
|JARMARI HEALTH POST
|FANDUM HEALTH POST
|MATTAFARI BASIC HEALTH CLINIC
|KIRI KASAMMA PRIMARY HEALTH CENTRE
|MADACHI BASIC HEALTH CLINIC
|MARMA BASIC HEALTH CLINIC
|SALERI HEALTH POST
|TASHEGUWA HEALTH POST
|TURABU PRIMARY HEALTH CENTRE
	KIYAWA	ANDAZA PRIMARY  HEALTH CLINIC
|BALAGO BASIC HEALTH CLINIC
|FAKE PRIMARY  HEALTH CLINIC
|GARKO PRIMARY HEALTH CLINIC
|KATANGA PRIMARY HEALTH CENTRE
|KATUKA PRIMARY HEALTH CLINIC
|KIYAWA PRIMARY HEALTH CENTRE
|KWANDA PRIMARY  HEALTH CLINIC
|MAJE KIYAWA PRIMARY HEALTH CLINIC
|SHUWARIN PRIMARY HEALTH CLINIC
|TSIRMA PRIMARY  HEALTH CLINIC
	MAIGATARI	BOTSUWA HEALTH CLINIC
|DANKUMBO HEALTH POST
|GALADI BASIC HEALTH CLINIC
|JAJERI BASIC HEALTH CLINIC
|KUKAYASKU DUYA BASIC HEALTH CLINIC
|MADANA BASIC HEALTH CLINIC
JIGAWA|MAIGATARI PRIMARY HEALTH CENTRE
|S/MAJA HEALTH CLINIC
|MATOYA BASIC HEALTH CLINIC
|KUKA-YASKU BASIC HEALTH CLINIC
	MALAM MADORI	AGIN BASIC HEALTH CLINIC
|DUNARI HEALTH POST
|BULAKORI HEALTH CLINIC
|GARUN GABAS PRIMARY HEALTH CENTRE
|MAIRAKUMI HEALTH POST
|MAKADDARI PRIMARY HEALTH CENTRE
|MALAM MADORI PRIMARY HEALTH CENTRE
|SHAYYA PRIMARY HEALTH CENTRE
|TAGWARO PRIMARY HEALTH CENTRE
|TASHENA PRIMARY HEALTH CENTRE
|GANDUN SARKI BASIC HEALTH CLINIC
	MIGA	DANGYATIN PRIMARY  HEALTH CENTER
|TAKALAFIYA HEALTH CLINIC
|GWARI HEALTH POST
|HANTSU PRIMARY  HEALTH CARE CENTER
|KOYA HEALTH CLINIC
|MIGA PRIMARY HEALTH CENTRE
|SABON GARI PRIMARY  HEALTH CLINIC
|SANSANI PRIMARY  HEALTH CENTER
|TSAKUWAWA PRIMARY HEALTH CCENTER
|YANDUNA PRIMARY  HEALTH GENTER
|ZAREKU HEALTH CLINIC
	RINGIN	CHAICHAI HEALTH CLINIC
|DABI PRIMARY HEALTH CARE CENTER
|KAFIN BABUSHE BASIC HEALTH CLINIC
|KARSHI BASIC HEALTH CLINIC
|KYARAMA BASIC HEALTH CLINIC
|WALAWA PRIMARY HEALTH CENTER
|SANKARA  PRIMARY HEALTH CENTER
|KARWAI PRIMARY HEALTH CENTER
|SHANGEL PRIMARY HEALTH CENTER
|YANDUSTE PRIMARY HEALTH CLINIC
	RONI	AMARYAWA PRIMARY HEALTH CENTRE
|NANUMAWA HEALTH CLINIC
|DANSURE PRIMARY HEALTH CLINIC
|GORA PRIMARY HEALTH CLINIC
|BASHE PRIMARY HEALTH CLINIC
|RONI PRIMARY HEALTH CENTRE
|SANKAU PRIMARY HEALTH CLINIC
|TAKURDAWA PRIMARY HEALTH CLINIC
|YASSARA PRIMARY HEALTH CLINIC
|ZUGAI PRIMARY HEALTH CLINIC
JIGAWA	SULE-TANKARKAR	ALBASU BASIC HEALTH CENTRE
|AMANGA PRIMARY HEALTH CENTER
|HANNUN GIWA PRIMARY HEALTH CENTRE
|DANLADI BASIC HEALTH CLINIC
|DANZOMO PRIMARY HEALTH CENTRE
|JEKE PRIMARY HEALTH CENTRE
|SHABARU HEALTH POST
|SULE PRIMARY HEALTH CENTRE
|TAKATSABA PRIMARY HEALTH CENTRE
|YANDAMO  PRIMARY HEALTH CLINIC
	TAURA	AJAURA PRIMARY HEALTH CENTRE
|CHAKWAIKWAIWA HEALTH POST
|CHUKUTO PRIMARY HEALTH CLINIC
|GUJUNGU HEALTH CLINIC
|KIRI PRIMARY HEALTH CLINIC
|KWALAM PRIMARY HEALTH CENTRE
|TSADAWA HEALTH CLINIC
|MAJIYA PRIMARY HEALTH CLINIC
|SABON GARIN YA"YA PRIMARY HEALTH CLINIC
|TAURA PRIMARY HEALTH CENTRE
	YANKWASHI	ACHILAFIYA PIMARY HEALTH CLINIC
|DANKARI PRIMARY HEALTH  CLINIC
|DAWAN GAWO PRIMRY HEALTH POST
|GURJIYA PRIMARY HEALTH CLINIC
|RAUDA PRIMARY HEALTH CLINIC
|KARKARNA BASIC HEALTH CLINIC
|KUDA  PRIMARY HEALTH CLINIC
|RINGIM PRIMARY HEALTH CLINIC
|YANKWASHI PRIMARY HEALTH CLINIC
|FIRJI GABAS HEALTH POST
|
KADUNA	BIRNIN GWARI	ANGUWAN HALADU PRIAMRY HEALTH CENTRE
|BIRNIN GWARI MCH
|JIBRIL MAIGWARI GENERAL HOSPITAL
|KAKANGI PRIMARY HEALTH CENTRE (BIRNIN GWARI)
KADUNA	CHIKUN	TUDUN WADA KUJAMA PRIMARY HEALTH CENTRE
|MARARRABAN RIDO PRIMARY HEALTH CENTRE
|NASSARAWA PRIMARY HEALTH CENTRE (CHIKUN)
|ROMI PRIMARY HEALTH CENTRE
|SABON TASHA GENERAL HOSPITAL
|SABON TASHA PRIMARY HEALTH CENTRE
|PHC SABON GARI
|HEALTH CLINIC KUJAMA GARI
KADUNA	GIWA	AHMADU BELLO UNIVERSITY TEACHING HOSPITAL
|GIWA GENERAL HOSPITAL
|GIWA PRIMARY HEALTH CENTRE
|KAYA PRIMARY HEALTH CENTRE
KADUNA	IGABI	JAJI COMPREHENSIVE HEALTH CENTRE
|JAJI MRS
|NDA NEW SITE CLINIC
|RIGASA (MIYATTI ALLAH) PRIMARY HEALTH CENTRE
|PHC RIGACHIKU
|PHC TURUNKU
|RIGASA GENERAL HOSPITAL
KADUNA	 IKARA	IKARA PRIMARY HEALTH CENTRE
|JAMPALAN GENERAL HOSPITAL
|IKARA
|PAKI PRIMARY HEALTH CENTRE
KADUNA	JABA	DADDU PRIMARY HEALTH CENTRE
|KWOI GENERAL HOSPITAL
|KWOI PRIMARY HEALTH CENTRE
|PRIMARY HEALTH CENTRE FAI
KADUNA	JEMA'A	ANGUWAN FARI PRIMARY HEALTH CENTRE
|BARDE PRIMARY HEALTH CENTRE
|FADAN KAGOMA RURAL HOSPITAL
|GODOGODO PRIMARY HEALTH CENTRE
|SIR PARTRIC IBRAHIM YAKOWA MEMORIAL HOSPITAL KAFANCHAN
|PHC JAGINDI
|KAFANCHAN PRIMARY HEALTH CENTRE
KADUNA	KACHIA	AGUNU DUTSE PRIMARY HEALTH CENTRE
|ARTILLERY BARRACKS CLINIC
|CROSSING HEALTH CLINIC
|GENERAL HOSPITAL GUMEL
|KACHIA PRIMARY HEALTH CENTRE
KADUNA	KADUNA NORTH	1 DIVISION MEDICAL CENTRE
|BADARAWA PRIMARY HEALTH CENTRE
|BARAU DIKKO TEACHING HOSPITAL
|DOKA (ZAKARI ISAH) PRIMARY HEALTH CARE CENTRE
|NAF BASE CLINIC
|PHC UNGUWAN SHANU
|PHC UNGUWAN RIMI
|PHC WARRI SREET
|KAWO GENERAL HOSPITAL
KADUNA	KADUNA SOUTH	BA 44 NIGERIAN ARMY REFERENCE HOSPITAL KADUNA
|DR GWAMNA AWAN GENERAL HOSPITAL
|ST GERARD CATHOLIC HOSPITAL
|TELEVISION PRIMARY  HEALTH CENTER
|PHC UNGUWAN MUAAZU
|UNGUWAR SANUSI PRIMARY HEALTH CENTRE
|YUSUF DANTSOHO GENERAL HOSPITAL
|AKOTI PRIMARY HEALTH CENTRE
KADUNA	KAGARKO	JERE PRIMARY HEALTH CENTRE
|KAGARKO GENERAL HOSPITAL
|KAGARKO PRIMARY HEALTH CENTRE
|KUBACHA PRIMARY HEALTH CENTRE
|KURMIN JIBRIN PRIMARY HEALTH CENTRE
KADUNA	KAJURU	IDON RURAL HOSPITAL
|KASUWAN MAGANI PRIMARY HEALTH CENTRE
|MARARABAN KAJURU MATERNAL AND CHILD HEALTH CLINIC
KADUNA	KAURU	DAMAKASUWA PRIMARY HEALTH CENTER
|RURAL HOSPITAL  (KAURU)
|DANDAURA PRIMARY HEALTH CENTER
|PRIMARY HEALTH CENTER KAURU
KADUNA	KAURA	FADA MATERNAL& CHILD HEALTH CLINIC
|KADARKO PHC
|KAURA RURAL HOSPITAL
|MANCHOCK PHC
KADUNA	KUBAU	ANCHAU PRIMARY HEALTH CENTRE
|KUBAU PRIMARY HEALTH CENTRE
|PAMBEGUA RURAL HOSPITAL
|PAMBEGUA PRIMARY HEALTH CENTRE
KADUNA	KUDAN	HUNKUYI GENERAL HOSPITAL
|HUNKUYI PRIMARY HEALTH CENTRE
|KAURAN WALI MODEL PRIMARY HEALTH CENTRE
KADUNA	LERE	ANGUWAR BAWA PRIMARY HEALTH CENTRE
|DAN-ALHAJI PRIMARY HEALTH CENTRE
|DOKAN LERE HEALTH CLINIC
|DMLM HOSPITAL SAMINAKA
|SAMINAKA COMPREHENSIVE HEALTH CENTRE
KADUNA	MAKARFI	DANGUZURI PRIMARY HEALTH CENTRE
|GAZARA PRIMARY HEALTH CENTRE
|MAKARFI GENERAL HOSPITAL
|GWANKI PRIMARY HEALTH CENTRE
KADUNA	SABON GARI	ABDULKWARI PRIMARY HEALTH CENTRE
|BASAWA PRIMARY HEALTH CENTRE
|BASAWA MILITARY POLICE
|JUSHI PRIMARY HEALTH CARE CENTRE
|DEPOT NA/NMS MEDICAL CENTRE
|KWATA FAMILY HEALTH UNIT
|GOVERNMENT HEALTH OFFICE
|PHC MUCHIA
|MAJOR IBRAHIM GENERAL HOSPITAL
|SAMARU PRIMARY HEALTH CENTRE
KADUNA	SANGA	AYU HEALTH CLINIC
|GWANTU GENERAL HOSPITAL
|GWANTU PRIMARY HEALTH CENTRE
|KARSHI DAJI HEALTH CLINIC
KADUNA	SOBA	RICHIFA PRIMARY HEALTH CENTRE
|SOBA PRIMARY HEALTH CENTRE
|RURAL HOSPITAL MAIGANA
|YAKASAI PRIMARY HEALTH CENTRE
KADUNA	ZANGON KATAF	AGUWAN RIMI PRIMARY HEALTH CENTRE
|KAMURU PRIMARY HEALTH CENTRE
|MADAKIYA PRIMARY HEALTH CENTRE
|ST LOUIS HOSPITAL (ZONKWA)
|ZANGON KATAF GENERAL HOSPITAL
|ZONKWA PRIMARY HEALTH CENTRE
KADUNA	ZARIA	ABUTH TUDUN WADA
|BABBAN DODO PRIMARY HEALTH CENTRE
|HGSH KOFAR GAYAN
|RIMIN DOKO PRIMARY HEALTH CENTRE
|CHC SAYE
|ST LUKES HOSPITAL, WUSASA
|
KANO	AJINGI	AJINGI COTTAGE
KANO	ALBASU	ALBASU PHC
|FARAGAI HP
KANO	BAGWAI	ABBAS PHC
KANO	BEBEJI	BEBEJI GENERAL HOSPITAL 
|RAHAMA PHC
KANO	BICHI	BICHI GENERAL HOSPITAL
|SAYE PHC
KANO	BUNKURE	BUNKURE PHC
|KUMURYA PHC
KANO	DALA	DALA MCH
|DALA NOH
|MSGH
|YALWA PHC
|KURNA PHC
|DALA MCH
KANO	DAWAKIN KUDU	DAWAKI GENERAL 1
|DAWAKI GENERAL 2
|TSAKUWA PHC
KANO	DANBATTA	DANBATTA GENRAL HOSPITAL
|SAN SAN MPHC
|FAGWALAWA COTTAGE
KANO	DAWAKIN TOFA	DAWAKIN TOFA GENERAL HOSPITAL
|DAWANAU PHC
KANO	DOGUWA 	RIRUWAI PHC
|FALGORE PHC
KANO	FAGGE	KWACHIRI TEAM 1
|KWACHIRI TEAM 2
|KWACHIRI TEAM 3
|SHEIK JIDDA TEAM 1
|SHEIK JIDDA TEAM 2
|SHEIK JIDDA TEAM 3
|MIDDLE ROAD TEAM 1
|MIDDLE ROAD TEAM 2
|RIJIYAR LEMO 1
|RIJIYAR LEMO 2
|MIDDLE ROAD MCH TEAM 
KANO	GABASAWA	GABASAWA PHC 
|ZAKIRAI CHC
KANO	GARKO	GARKO BHC
|DAL PHC
KANO	GARUN MALAM	GARUN MALLAM PHC
|YADAKWARI   PHC
KANO	GAYA	GAYA PHC
|KADEMI PHC
KANO	GEZAWA	TSAMIYA BABBA
|GEZAWA GEN. HOSP.
KANO	GWALE	KABUGA PHC 
|JAEN PHC
|GORON DUTSE PHC
|FUSKAR YAMMA PHC
|MANGWARORI
|KABUGA B.
|JA'EN B.
KANO	GWARZO	GWARZO GEN. HOSPITAL
|KUTAMA MPHC
KANO	KABO	KABO COTTAGE
|GARO MPHC
KANO	KARAYE	KWANYAWA PHC
|MAGAJIN GARI PHC
KANO	KIBIYA	KIBIYA PHC
KANO	KIRU	KIRU GENERAL
|YAKO PHC
|YALWA PHC
KANO	KMC	MARMARA MCH TEAM 1
|MARMARA MCH TEAM 2
|HASIYA BAYERO TEAM 1
|HASIYA BAYERO TEAM 2
|MMSH TEAM 1
|MMSH TEAM 2
|MMSH TEAM 3
|SHARADA PHC TEAM 1
|SHARADA PHC TEAM 2
|SHARADA PHC TEAM 3
|SABO BAKIONZUWO TEAM 1
|SABO BAKIONZUWO TEAM 2
KANO	KUMBOTSO	CHIRANCHI WARD
|SHEKA PHC
|KUMBOTSO CHC
|MARIRI PHC
|NAIBAWA PHC
KANO	KUNCHI	KUNCHI PHC
KANO	KURA	KURA GENERAL HOSPITAL
|DANHASSAN PHC
KANO	MADOBI	AKILU MEM PHC SUPER SITE
|KWANKWASO COTT
KANO	MAKODA	MAKODA PHC
|KOGUNA PHC
KANO	MINJIBIR	MINJIBIR GEN. HOSP.
|GAWUNA TEAM ONE POLICE CLINIC
|GAWUNA TEAM TWO 
|GAWUNA TEAM THREE
|GAWUNA TEAM FOUR
|GAWUNA TEAM FIVE
KANO	NASSARAWA	GIGINYU ABDULLAHI WASE T.H. TEAM 1
|GIGINYU ABDULLAHI WASE T.H. TEAM 2
|E.O.C TEAM 1
|E.O.C TEAM 2
|MUHAMMADU BUHARI T.H TEAM 1
|MUHAMMADU BUHARI T.H TEAM 2
|HOTORO NORTH TEAM 1
|HOTORO NORTH TEAM 2
|HOTORO NORTH TEAM 3
|KAURA GOJE TEAM 1
|KAURA GOJE TEAM 2
KANO	RANO	RANO S/GARI PHC
|RURUMS/ GARI PHC
KANO	RIMIN GADO	RIMIN GADO PHC
KANO	ROGO	ROGO GENERAL HOSPITAL 
|ROGO GENERAL HOSPITAL 
|ZAREWA BHC
|BARI MPHC
KANO	SHANONO	SHANONO PHC
|FARURUWA PHC
KANO	SUMAILA	SUMAILA GENARAL HOSPITAL
|RIMI BHC
KANO	TAKAI	TAKAI NYSC PHC
|KACHAKO PHC
KANO	TARAUNI	SHEIKH ISYAKU RABIU P HOSP 1
|SHEIKH ISYAKU RABIU P HOSP 2
|AMINU KANO TEACHING HOSP 1
|HOTORO HEALTH CLINIC 
|UNGUWA UKU PHC
|UNGUWA UKU PHC
|JAOJI  PHC
KANO	TOFA	TOFA MPHC
KANO	TSANYAWA	TSANYAWA CHC
|GURUM MPHC
KANO	TUDUN WADA	JANDUTSE PHC
|YARYASA PHC
KANO	UNGOGO	RIJIYAR ZAKI
|WAZIRI GIDADO BACHIRAWA
|ZANGO
|YADAKUNYA
KANO	WARAWA	WARAWA PHC
|TAMBURAWA GABAS PHC
|YANDALLA POLAC
KANO	WUDIL	WUDIL GENARAL HOSPITAL
|
KATSINA	BAKORI	GUGA PHC
|BAKORI PRIMARY HEALTH CARE 
KATSINA	BATAGARAWA	PHC AJIWA
|BATAGARAWA COMPREHENSIVE HEALTH CENTRE
KATSINA	BATSARI	CHC WAGINI
|BATSARI GENERAL HOSPITAL 
KATSINA	BAURE	CHC BABBAN MUTUM
|BAURE GENERAL HOSPITAL 
KATSINA	BINDAWA	PHC DORO
|BINDAWA COMPREHENSIVE HEALTH CENTRE
KATSINA	CHARANCHI	MPHC KURAYE
|TSAKATSA HEALTH CLINIC
KATSINA	DAN MUSA	CHC YANTUMAKI
|DANMUSA GENERAL HOSPITAL 
KATSINA	DANDUME	PHC MAHUTA
|DANDUME COMPREHENSIVE HEALTH CENTER 
KATSINA	DANJA	PHC DABAI
| DANJA COMPREHENSIVE HEALTH CENTRE
KATSINA	DAURA	CHC DAURA
|DAURA GENERAL HOSPITAL
KATSINA	DUTSI	MPHC SHARGALLE
|DUTSI COMPREHENSIVE HEALTH CENTRE 
KATSINA	DUTSIN MA	CHC DUTSANMA
|DUTSANMA COMPREHENSIVE HEALTH CENTRE 
KATSINA	FASKARI	PHC YANKARA
|FASKARI COMPREHENSIVE HEALTH CENTRE 
KATSINA	FUNTUA	GENERAL HOSPITAL FUNTUA
|FUNTUA COMPREHENSIVE HEALTH CENTRE 
KATSINA	INGAWA	CHC YANDOMA
| GENERAL HOSPITAL INGAWA
KATSINA	JIBIA	PHC RIKO
|COMPREHENSIVE HEALTH CENTRE MAGAMA  
KATSINA	KAFUR	HC DANKANJIBA
|COMPREHENSIVE HEALTH CENTRE KAFUR 
KATSINA	KAITA	PHC DANKAMA
|COMPREHENSIVE HEALTH CENTRE  KAITA 
KATSINA	KANKARA	PHC YARGOJE
|GENERAL HOSPITAL - KANKARA 
KATSINA	KANKIA	PHC RIMAYE
|GENERAL HOSPITAL - KANKIA 
KATSINA	KATSINA	GENERAL HOSPITAL KATSINA
|CHC KOFAR KAURA 
|MCHC KOFAR MARUSA 
|TURAI MCH
KATSINA	KURFI	PHC RAWAYAU
|GENERAL HOSPITAL  - KURFI 
KATSINA	KUSADA	MPHC DUDUNNI
|COMPREHENSIVE HEALTH CENTRE  - KUSADA 
KATSINA	MAI'ADWA	MCH KONGWALAM
|COMPREHENSIVE HEALTH CENTRE  - MAIADUA 
KATSINA	MALUMFASHI	PHC DAYI
|GENERAL HOSPITAL - MALUMFASHI 
KATSINA	MANI	CHC JANI
|GENERAL HOSPITAL - MANI 
KATSINA	MASHI	MCH MAJIGIRI
|COMPREHENSIVE HEALTH CENTRE  - MASHI 
KATSINA	MATAZU	MPHC MAZOJI
|COMPREHENSIVE HEALTH CENTRE  - MATAZU 
KATSINA	MUSAWA	CHC MUSAWA
|GENERAL HOSPITAL - MUSAWA 
KATSINA	RIMI	PHC MAKURDA
| GENERAL HOSPITAL - RIMI
KATSINA	SABUWA	PHC MACHIKA
|COMPREHENSIVE HEALTH CENTRE  - SABUA 
KATSINA	SAFANA	PHC ZAKKA
|COMPREHENSIVE HEALTH CENTRE  - SAFANA 
KATSINA	SANDAMU	MCHC FAGO
|COMPREHENSIVE HEALTH CENTRE  - SANDAMU 
KATSINA	ZANGO	ROGOGO PHC
|MODEL PRIMARY HEALTH CENTRE -  ZANGO 
|
KEBBI	ALEIRO	ALEIRO GENERAL HOSPITAL
KEBBI	AREWA	KANGIWA PRIMARY HEALTH CENTRE
KEBBI	ARGUNGU	ARGUNGU GENERAL HOSPITAL
|ARGUNGU MATERNAL AND CHILD HEALTH CENTRE
KEBBI	AUGIE	AUGIE PRIMARY HEALTH CENTRE
KEBBI	BAGUDO	BAGUDO MATERNAL AND CHILD HEALTH CLINIC
|LAFAGU PRIMARY HEALTH CENTRE
|PHC ILLO
KEBBI	BIRNIN KEBBI	BADARIA PRIMARY HEALTH CENTRE
|BIRNIN KEBBI FEDERAL MEDICAL CENTRE
| TAKALAU PRIMARY HEALTH CARE 
| SIR YAHAYA GENERAL HOSPITAL
KEBBI	BUNZA	 BUNZA PRIMARY HEALTH CENTRE
| RAHA PRIMARY HEALTH CENTRE
KEBBI	DANDI	 KAMBA GENERAL HOSPITAL
KEBBI	DANKO/WASAGU	 RIBAH MATERNAL AND CHILD PRIMARY HEALTH CENTRE
| WASAGU PRIMARY HEALTH CENTRE
KEBBI	FAKAI	 MATUTA PRIMARY HEALTH CARE
KEBBI	GWANDU	 DALIJAN PRIMARY HEALTH CENTRE
| GWANDU PRIMARY HEALTH CENTRE
KEBBI	JEGA	 BIRNIN YARI PRIMARY HEALTH CENTRE
| JEGA GENERAL HOSPITAL
KEBBI	KALGO	 KALGO MATERNAL AND CHILD HEALTH CLINIC
KEBBI	KOKO/BASSE	 BESSE MATERNAL AND CHILD PRIMARY HEALTH CENTRE
| KOKO GENERAL HOSPITAL
KEBBI	MAIYAMA	 MAIYAMA GENERAL HOSPITAL
KEBBI	NGASKI	 BIRNIN YAURI HEALTH POST
| WARA GENERAL HOSPITAL
KEBBI	SAKABA	 DIRIN DAJI GENERAL HOSPITAL
| MAKUKU PRIMARY HEALTH CENTRE
KEBBI	SHANGA	 GIRON MASA PRIMARY HEALTH CENTRE
| SHANGA GENERAL HOSPITAL
KEBBI	SURU	 DAKINGARI PRIMARY HEALTH CENTRE
KEBBI	YAURI	 YAURI MATERNAL AND CHILD PRIMARY HEALTH CENTRE
| ZAMARE MODEL PRIMARY HEALTH CENTRE
KEBBI	ZURU	 RIKOTO PRIMARY HEALTH CENTRE
| SENCHI BAMAIYI SUNDU GENERAL HOSPITAL
|
KOGI	ADAVI	UTOHU PHC
KOGI	AJEOKUTA	GEREGU PHC
KOGI	ANKPA	OWELLE PHC
|EJINYA OKENYI PHC
KOGI	BASSA	OGUMA PHC
KOGI	DEKINA	ANYIGBA CHC
|ETUTEKPE PHC
KOGI	IBAJI	ONYEDEGA PHC
KOGI	IDA	KO FAMILY HEALTH CENTRE
KOGI	IGALAMELA	AJAKA PRIMARY HEALTH CENTRE
KOGI	IJUMU	AIYETORO PRIMARY HEALTH CENTRE
KOGI	KABBA	OWODE MATERNAL AND CHILD HEALTH CLINIC
KOGI	KOGI	FAMILY SUPPORT PROGRAM CLINIC KOTON-KARFE
KOGI	LOKOJA	ADANKOLO PRIMARY HEALTH CENTRE
| FELELE FAMILY SUPPORT PROGRAMME CLINIC 
|KOGI SPECIALIST HOSPITAL, LOKOJA
KOGI	MOPA-MURO	ILELEJU BASIC HEALTH CLINIC
KOGI	OFU	UGWOLAWO PRIMARY HEALTH CENTRE
KOGI	OGORI MAGONGO	OKIBO PRIMARY HEALTH CENTRE
KOGI	OKEHI	OKAITO PRIMARY HEALTH CENTRE
KOGI	OKENE	OKENE MATERNAL AND CHILD HEALTH CLINIC
KOGI	OLAMABORO	INELE UGO PRIMARY HEALTH CENTRE
|EMONYOKWU PRIMARY HEALTH CENTRE (KO OGUGU 3 WARD)
KOGI	OMALA	ECHA PRIMARY HEALTH CENTRE
|IBADO PRIMARY HEALTH CENTRE (KO OKPACHA WARD)
KOGI	YAGBA WEST	PALACE CLINIC
KOGI	YAGBA EAST	IFEOLUKOTUN DHU
|OMOWA-MOPO BASIC HEALTH CLINIC (KO MOPO WARD 09)
|
KWARA	ASA	DHU AFON
|ALAPA BHC
|OGELE PHC
KWARA	BARUTEN	PHC KOSUBOSU
|GEN. HOSP. OKUTA
|GWANARA BHC
KWARA	EDU	LAFIAGI GEN HOSP
|TSHARAGI MAT
|SHONGA MAT
KWARA	EKITI	EKITI LGA SECRETATRIAT
KWARA	IFELODUN	SHARE GEN HOSO
|IDOFIAH PHC
|BABANLA PHC
KWARA	ILORIN EAST	OKELE PHC
|UITH
|ILE APA HC
|IPONRIN BHC
|OJA GBORO PHC
|AGBEYANGI HC
KWARA	ILORIN SOUTH	CIVIL SERVICE HOSP
|SOBI SPECIALIST
|ERO OMO
|OLUFADI PHC
|TANKE PHC
|SOBI SPECIALIST
|AMILENGBE MAT
|CENTRE IGBORO
KWARA	ILORIN WEST 	OKO ERIN PHC
|ADEWOLE COTTAGE
|GENERAL HOSP
|OFFA GARAGE BHC
|PAKATA PHC
|OGIDI BANI BHC
|ADEWOLE PHC
|ALANAMU PHC
|BABOKO BHC
|AJIKOBI PHC
KWARA	IREPODUN	OFE ARN PHC
|IJOMU PHC
|AJASE PHC
KWARA	ISIN	OWU LGA SECRETARIAT
KWARA	KAIAMA	KAIAMA MAT CEN
|GWARIA PHC
|BANI PHC
KWARA	OFFA	OFFA GEN HOSP
|ABOGUNUGUN PHC
KWARA	MORO	SHAO BHC
KWARA	OKE-ERO	ILOFA ODO OWA HC
KWARA	OYUN	 IJAGBO PHC
| ERIN GEN HOSP
KWARA	PATIGI	PATIGI GEN HOSP
|LADE COTTAGE
|KPADA MPHC
|
LAGOS	AGEGE	SANGO PHC
|POWERLINE PHC
LAGOS	AJEROMI/IFELODUN	AKERE PHC
|LAYENI PHC
|SIGNALS OPERATION COMMAND CLINIC
|OBISESAN NAVAL MEDICAL CENTRE
|AJEROMI GH
LAGOS	ALIMOSHO	AKOWONJO PHC
|AGBADO PHC
|HELEN ADERONKE PHC
|IPAJA PHC
|ISHERI OLOFIN PHC
|RAUF AREGBESOLA PHC 
|IPINLERERE PHC
|ALIMOSHO GH
|NIGERIAN NAVY SICKBAY
|NAF MEDICAL CENTRE SHASHA
LAGOS	AMUWO ODOFIN	BAT PHC
|AGBOJU PHC
|FESTAC PHC
|NIGERIAN NAVY REFERENCE HOSPITAL
LAGOS	APAPA	OLOJOWON PRIMARY HEALTH CENTRE
|IJORA OLOYE PHC
|CFO MRS MILITARY HOSPITAL
LAGOS	BADAGRY	APA PHC
|ILADO PHC
|NAF MOTHER & CHILD HOSP
LAGOS	EPE	AGBOWA PHC
|EPE PHC
|AGBOWA GH
|ORIYANRIN PHC
|BADORE PHC
|IGBO EFON PHC
|IKOYI PHC
LAGOS	ETIOSA	IKATE PHC
|SANGOTEDO PHC
|MCC
|POLICE HOSPITAL
|65 BATALLION MRS HOSPITAL
LAGOS	IBEJU LEKKI	IBEJU PHC
|AKODO GH
LAGOS	IFAKO/IJAYE	AGBADO KOLA PHC
|IFAKO PRIMARY HEALTH CENTRE
|IFAKO GH
LAGOS	IKEJA	OJODU PHC
|ONILEKERE PHC
|OREGUN PHC
|LASUTH
|9BMC ARMY CANTONMENT IKEJA
LAGOS	IKORODU	IMOTA PHC
|IPAKODO PHC
|IKORODU/ITA ELEWAPHC
|IGBOGBO PHC
|OKE ELETU PHC
|174 BATALLION CHILD HEALTH CARE
LAGOS	KOSOFE	OGUDU PHC
|KETU PHC
|IKOSI PHC
|GBAGADA GH
LAGOS	LAGOS ISLAND	SURA PHC
|OLOWOGBOWO PHC
|LIMH
|ABULE NLA PHC
|SIMPSON PHC
|IWAYA PHC
|FEDERAL MEDICAL CENTRE EBUTE METTA
LAGOS	LAGOS MAINLAND	INFECTIOUS DISEASE HOSPITAL 
|PSYCHIATRIC HOSPITAL
|YABA 68 NIG ARMY REFERENCE HOSPITAL
LAGOS	MUSHIN	KAJOLA PHC
|PALM AVENUE PHC
|LUTH
|ISHAGIRA PHC
|IMUDE PHC
|IBA PHC
LAGOS	OJO	OTTO/IJANIKIN PHC
|OJO PHC
|149 BATTALION MRS
|NAVY HOSPITAL
|IYANA-EJIGBO PHC
|OSHODI PHC
LAGOS	OSHODI	ILASA PHC
|SHOGUNLE  IKEJA NAF
|PORT HEALTH
LAGOS	SHOMOLU	AKOKA PHC
|CMS PHC
LAGOS	SURULERE	AKERELE PHC
|ORILE IGANMU PHC
|
NASARAWA	AKWANGA	GENERAL HOSPITAL AKWANGA
|PHC RINZE
|PHC ANDAHA
NASARAWA	AWE	GENERAL HOSPITAL AWE
|MPHC BAURE
|PHC AZARA
NASARAWA	DOMA	TOWN CLINIC DOMA
|PHC ALARAMA
|PHC MODEL 
NASARAWA	KARU	PHC KARU
|MEDICAL CENTER MARARABA
|GENERAL HOSPITAL UKE
|GENERAL HOSPITAL PANDA
NASARAWA	KEANA	GENERAL HOSPITAL KEANA
|PHC AMIRI
NASARAWA	KEFFI	FMC KEFFI
|PHC ANG WAJE
|PHC KOFAR PADA
|PHC JIGWADA
|PHC SABON GARI
NASARAWA	KOKONA	GENERAL HOSPITAL GARAKU
|PHC ANG WAJE
|PHC KOFAR PADA
|PHC JIGWADA
|PHC SABON GARI
NASARAWA	LAFIA	DASH LAFIA
|NMPHC AGWADA
|PHC BASSA
NASARAWA	NASARAWA	PHC PADA
|PHC DOMA ROAD
|PHC BAKIN RIJIYA
|SHABU COMPREHENSIVE
|PHC BAD
|PHC FADAMA NORTH
NASARAWA	NAS/EGGON	PHCC NASS EGGON
|PHC1 LOKO
|PHC LAMINGA
|PHC MARARABA UDEGE
NASARAWA	OBI	GENERAL HOSPITAL OBI
|PHC DUDUGURU
|PHC DADDARE
|PHC AGYARAGU
NASARAWA	TOTO	GENERAL HOSPITAL TOTO
|BHC(FMC) GADABUKE
|MODEL PHC UMAISHA
NASARAWA	WAMBA	GENERAL HOSPITAL WAMBA
|MODEL PHC WAMBA
|
NIGER	RAFI	PHC ADAMU TURAK
|PHCC TEGINA
NIGER	AGWARA	CHC AGWARA
|BHC GALLAH
NIGER	SULEJA	DIJE BALA BHC
|GENERAL HOSPITAL SULEJA
NIGER	CHANCHAGA	OLD AIR PORT CLINIC
|TUNGA CLINIC
|GENERAL HOSPITAL
NIGER	RIJAU	GENERAL HOSPITAL T/M
|MCH RIJAU
NIGER	BOSSO	MAIKUNKELE PHC
|MAITUMBI PHC
NIGER	LAVUN	MCH KUTIGI
|PHCC NDARUKA
|PHCC DOKO
NIGER	TAFA	BHC WUSE
|MPHC  GAURAKA
NIGER	WUSHISHI	PHCC WUSHISHI
|PHCC ZUNGERU
NIGER	GURARA	FMC GAWU BABANGIDA
|PHCC DIKO
NIGER	PAIKORO	TOWN CLINIC PAIKO
|PHCC KAFFIN KORO
NIGER	MARIGA	CHC MARIGA
|MCH BANGI
NIGER	EDATI	CHC ENAGI
|ETSUWORO NPHCC
NIGER	MOKWA	GENERAL HOSPITAL MOKWA
|PHCC KUDU
|PHCC GBARA
NIGER	MAGAMA	BHC SALKA
|BHC NASKO
NIGER	KONTAGORA	CENTRAL PHC
|GENERAL HOSPITAL
NIGER	SHIRORO	GENERAL HOSPITAL KUTA
|MCH GWADA
|ERENA MCH
NIGER	KATCHA	PHCC KATCHA
| BHC BADDEGI
NIGER	MUNYA	RURAI HOSPITAL SARKIN PAWA
|PHC DAZA
NIGER	AGAIE	 GENERAL HOSPITAL AGAIE
|PHC  LOGUMA
NIGER	GBAKO	MCH LEMU
|BHC EDOZHIGI
NIGER	BIDA	FMC BIDA 
|GEN HOSP BIDA 
NIGER	BORGU	FAMILY HEALTH CENTER NEW BUSSA
|GEN HOSP
|BHC WAWA
NIGER	LAPAI	GH LAPAI
|SAMINAKA PHCC
|GULU MCH
NIGER	MASHEGU	CPHC KABOJI
|MCH IBBI
|MPHC MAKERA
|
OGUN	ABEOKUTA NORTH	OG IBEREKODO GENERAL HOSPITAL
|OG IBEREKODO PRIMARY HEALTH CENTER
|OG ADEUN HEALTH CLINIC
|OG ISAGA ORILE GENERAL HOSPITAL
|OG ILE-ISE AWO HEALTH CLINIC
|OG IDI-EMI HEALTH CLINIC
|OG SABO HEALTH CLINIC
OGUN	ABEOKUTA SOUTH	OG ROYAL HEALTH POST
|OG STATE HOSPITAL IJAYE
|OG ABEOKUTA FEDERAL MEDICAL CENTRE
|OG KUGBA HEALTH CENTRE
|OG OBA ADEMOLA MATERNITY HEALTH CENTRE
|OG OKE ILEWO FAMILY HEALTH CENTRE
|OG SARAKI ADIGBE HEALTH CLINIC
OGUN	ADO ODO/OTA	OG ADO ODO PRIMARY HEALTH CENTRE
|OG AGBARA PRIMARY HEALTH CARE CENTRE
|OG IJOKO PRIMARY HEALTH CENTRE
|OG IYESI HEALTH CENTRE
|OG SANGO PRIMARY HEALTH CENTRE
OGUN	EWEKORO	OG ARIGBAJO PRIMARY HEALTH CENTRE
|OG ITORI PRIMARY HEALTH CARE
OGUN	IFO	OG OBADA PRIMARY HEALTH CENTRE
|OG AGBADO  PRIMARY HEALTH CENTRE
|OG IFO GENERAL HOSPITAL
|OG AJUWON PRIMARY HEALTH CENTRE
|OG IBOGUN MODEL PRIMARY HEALTH CENTRE
|OG OJODU ABIODUN PRIMARY HEALTH CENTRE
|OG OYERO HEALTH CENTRE
OGUN	IJEBU EAST	OG IMUSHIN HEALTH CENTRE
OGUN	IJEBU NORTH EAST	OG OGBERE HEALTH CLINIC
|OG ATAN GENERAL HOSPITAL
|OG ERUNWON HEALTH CLINIC
OGUN	IJEBU NORTH	OG ILESE HEALTH CLINIC
|OG ODEDEYO HEALTH CLINIC
|OG IJARI MODEL HEALTH CENTRE
|OG OKE-ODO HEALTH CLINIC
|OG IJEBU IGBO GENERAL HOSPITAL
|OG MAMU HEALTH CENTRE
OGUN	IJEBU ODE	OG AWA HEALTH CENTRE
|OG IJEBU-ODE  HOSPITAL
|OG OKE-OYINBO FAMILY HEALTH CENTRE
|OG ITA OSU HEALTH CENTRE
|OG ITA-ALAPO HEALTH CARE
OGUN	IKENNE	OG GENERAL HOSPITAL IKENNE
|OG GENERAL PRIMARY HEALTH CENTRE
OGUN	IMEKO AFON	OG IMEKO PRIMARY HEALTH CENTRE
|OG OWODE HEALTH CLINIC
OGUN	IPOKIA	OG IDIROKO GENERAL HOSPITAL
|OG IHUNBO HEALTH CLINIC
|OG IPOKIA GENERAL HOSPITAL
|OG MAUN HEALTH CLINIC
|OG TUBE HEALTH CLINIC
OGUN	OBAFEMI - OWODE	OG AJEBO HEALTH POST
|OG SIUN HEALTH CLINIC
|OG MOKOLOKI HEALTH CLINIC
|OG ADIGBE HEALTH CLINIC
OGUN	ODEDA	OG MOWE HEALTH POST
|OG OWODE GENERAL HOSPITAL
|OG CAMP (AYAA) CLINIC
|OG OBATONKO HEALTH CLINIC
|OG ODEDA GENERAL HOSPITAL
|OG BAKATARI HEALTH CLINIC
|OG ORILE - ILUGUN HEALTH CLINIC
OGUN	ODOGBOLU	OG OSIELE HEALTH CLINIC
|OG  ALA-IDOWA GENERAL  HOSPITAL
|OG MOBALUFON MODEL HEALTH CENTRE
|OG ODOGBOLU GENERAL HOSPITAL
OGUN	OGUN WATESIDE	OG ODOGBOLU PRIMARY HEALTH CENTRE
|OG OMU GENERAL HOSPITAL
|OG AYILA HEALTH CENTRE
|OG IBIADE GENERAL HOSPITAL
|OG IWOPIN COMPREHENSIVE HEALTH CENTRE
OGUN	REMO NORTH	OG ILARA HEALTH CENTRE
|OG IPARA PRIMARY HEALTH CENTER
|OG ODE PRIMARY HEALTH CENTRE
|OG OLABISI ONABANJO UNIVERSITY TEACHING HOSPITAL
|OG ODE LEMO GENERAL HOSPITAL
OGUN	SHAGAMU	OG OGIJO PRIMARY HEATH CARE
|OG SABO G.R.A HEALTH CLINIC
OGUN	YEWA NORTH	OG AYETORO GENERAL HOSPITAL
|OG OJA ODAN  RURAL HEALTH CENTRE
|OG IGBOGILA PRIMARY HEALTH CENTRE
OGUN	YEWA SOUTH	OG IJOUN PRIMARY HEALTH CENTRE
|OG OKE-ERINJA HEALTH CLINIC
|
ONDO	AKOKO NORTH EAST	BHC  JUBILEE
|ALAPATA BHC 
|BHC OKOJA
ONDO	AKOKO NORTH WEST	PHC OKEAGBE 
|PHC ISUA OKE 
|PH CENTRE AGBALUKU
|IREMU PHC
ONDO	AKOKO SOUTH WEST	PHC SABO IBAKA -OKA 
|BHC OBA OKETERE
|BHC AKUNGBA
ONDO	AKURE NORTH	CHC OBAILE 
|GENERAL HOSPITAL 
|PHC ALA IJAGBUSI
ONDO	AKURE SOUTH	CHC OKE IJEBU 
|ARAKALE CHC
|AWULW BHC
|ESURE BHC
|ADEGBOLA BHC
|MOTHER &CHILD
ONDO	ESE-ODO	CHC AROGBO 
|IGBEKEBO  BHC
|BHC BOLOWO BHC
ONDO	IDANRE	BHC ODO ODE
|BHC ALADE
|NPHCC OFOSU
ONDO	IFEDORE 	CHC ILARA 
|BHC MOLETE
|Ijare CHC
ONDO	ILAJE 	CHC IGBOKODA
|ZION PEPE PHC
|UGBONLA PHC
|MOLUTEHIN PHC
ONDO	ILEOLUJI/OKEIGBO 	BHC TEMIDIRE 
|OKEAALAFIA CHC
|OKEIGBO CHC
ONDO	IRELE	CHC ODE IRELE 
|BHC AYADI
|CHC AJAGBA
ONDO	ODIGBO	CHC ORE 
|ONIPARAG PHC
ONDO	AKOKO SOUTH EAST	OMIFON PHC
|GENERAL HOSPITAL /EPI UNIT
	OKITIPUPA	CHC EBUTE 
|BHC IKOYA
|BHC ERINJE
ONDO	ONDO EAST	NPI UNIT, GENERAL HOSPITAL 
|CHC EPE
ONDO	ONDO WEST	MPHC MAROKO 
|PHC AKINJAGUNLA
|PHC MOFERERE
|PHC BETTER LIFE
|JILALU BHC
ONDO	OSE	BHC IFON 
|BHC IDOANI
|BHC UTE
ONDO	OWO	PHC OKE MAPO 
|BHC IJEBU
|BHC USO
|
OSUN	ATAKUMOSA EEST	IWARA CHC
OSUN	ATAKUMOSA WEST	OKE OJA PHC OSU
OSUN	AYEDAADE	MGDS IJUGBE
|MGDS OKE ELU
OSUN	AYEDIRE	OKE ODO PHC
OSUN	BOLUWADURO	OMI ERAN PHC
OSUN	BORIPE	CHC IRE
|ISALE OYO PHC
OSUN	EDE NORTH	OJA TIMI PHC
OSUN	EDE SOUTH	COUTAGE  PHC
OSUN	EGBEDERO	AWO PHC
|IDO OSUN PHC
OSUN	EJIGBO	MODEL PHC
|POPO PHC
OSUN	IFE CENTRAL 	ADEREMI PHC
|OAUTHC 
|ENUWA PHC
OSUN	IFE EAST	OTUBU PHC
|MOORE PHC
OSUN	IFE NORTH 	MOORO PHC
|OKOOKO PHC
OSUN	IFE SOUTH	IFETEDO PHC
OSUN	IFEDAYO	OKE ILA PHC
OSUN	IFELODUN	OKEROKO PHC
|EMILOJU PHC 
OSUN	ILA	ADEKUNLE  PHC
OSUN	ILESA EAST	WESLEY GUILD HOSPITAL
|OPO PHC 
OSUN	ILESA WEST	ADETI PHC
OSUN	IROPODUN	AROMIWE PHC
OSUN	IREWOLE	AYEDAADE PHC
OSUN	ISOKAN	OKE ALFA PHC
OSUN	IWO	ALAAYE PHC
|FEESU PHC
|AGBERIRE
OSUN	OBOKUN	IBOKUN PHC
OSUN	ODO OTIN	MDG OKUKU PHC
|JAGUN OSI
OSUN	OLA OLUWA	OGBAAGBA PHC
OSUN	OLORUNDA	OSUN UTN
|SABO PHC
|OTA EFUN PHC
OSUN	ORIADE	IJESA JESA PHC
|IKEJI ARAKEJI
|IPETU IJESA 1 PHC
OSUN	OROLU	ELEESI  PHC
|ARAROMI PHC
OSUN	OSOGBO	ISALE AGBARA PHC
|ODO OLOWO PHC
|OKE ABESU PHC
|OKE BAALE PHC
|
 OYO	 AFIJIO	AWE PRIMARY HEALTH CENTRE
|FIDITI GENERAL HOSPITAL
|ILORA GENERAL HOSPITAL
|AKINMORIN PRIMARY HEALTH CENTRE
 OYO	AKINYELE	OLORISA-OKO PRIMARY HEALTH CENTRE
|MONIYA PRIMARY HEALTH CENTRE
|2ND MECHANIZED DIVISION MEDICAL HOSPTAL
|OJOO  PRIMARY HEALTH CENTRE
|AKINYELE PRIMARY HEALTH CENTRE
 OYO	ATIBA	BOROBORO HEALTH CENTRE
|KOSO PRIMARY  HEALTH CENTER
|OKE-OROKI HEALTH CENTRE
|AAFIN PRIMARY HEALTH CENTRE
|OKE OLOLA PRIMARY HEALTH CENTRE
 OYO	ATISBO	AGO ARE PRIMARY HEALTH CENTRE
|AGO ARE MODEL PRIMARY HEALTH CENTRE
|ADEOYE PRIMARY HEALTH CENTRE
|AGUNREGE  PRIMARY HEALTH CENTRE
|TEDE COMPREHENSIVE HEALTH CENTRE
 OYO	EGBEDA	APETE PRIMARY HEALTH CENTRE
 OYO	IBADAN NORTH EAST 	ATIPE HEALTH CENTRE
|AYEKALE PRIMARY HEALTH CENTRE
|IWO ROAD PRIMARY HEALTH CENTRE
|AREMO PRIMARY  HEALTH CENTRE
|ALAFARA PRIMARY HEALTH CENTRE
 OYO	IBADAN NORTH 	BASORUN PRIMARY HEALTH CENTRE
|AGO TAPA PRIMARY HEALTH CENTRE
|OBASA PRIMARY HEALTH CENTRE
|AGBOWO PHC
 OYO	IBADAN NORTH WEST 	POLICE HOSPITAL
|ONIYANRIN PRIMARY HEALTH CENTRE
|AYEYE PRIMARY HEALTH CENTRE
|KOSEUNTI PRIMARY HEALTH CENTRE
|MOKOLA ARMY BARRACK HOSPITAL
 OYO	IBADAN SOUTH EAST	AGBONGBON PIMARY HEALTH CENTRE
|EYIN GRAMER PRIMARY HEALTH CENTRE
|BOLUWAJI PRIMARY HEALTH CENTRE
|ELEKURO HEALTH CENTRE
|MAPO PRIMARY HEALTH CENTRE
 OYO	IBADAN SOUTH WEST	AKERE PRIMARY HEALTH CARE CENTRE
|AGBOKOJO PRIMARY HEALTH CENTRE
|AKURO PRIMARY  HEALTH CARE CENTRE
|AWODIFE PRIMARY HEALTH CARE  CENTRE
|OLUYOLE PRIMARY HEALTH  CARE CENTRE
 OYO	IBARAPA CENTRAL	IDERE MODEL PRIMARY HEALTH CENTRE
|IGBOLE PRIMARY HEALTH CENTRE
|OKE-ODO PRIMARY HEALTH CENTRE
|TOBALOGBO PRIMARY HEALTH CARE
|SEKERE HEALTH CLINIC
|ISALE OBA PRIMARY HEALTH CENTRE
|AKERORO HEALTH CLINC
 OYO	IBARAPA EAST	ALAPA PRIMARY HEALTH CENTRE
|ANKO  PRIMARY HEALTH CENTRE
|ERUWA GENERAL HOSPITAL
 OYO	IBARAPA NORTH	ABIDIOKI PRIMARY HEALTH CENTRE
|IGANGAN OKE OLA PRIMARY HEALTH CENTRE
|ASUNNARA PRIMARY HEALTH CENTRE
|TAPA PRIMARY HEALTH  CENTRE
 OYO	IDO	KOGUO HEALTH POST
|IDO PRIMARY HEALTH CENTRE
 OYO	IREPO	ATIPA PRIMARY HEALTH CENTRE
|AJANGBA PRIMARY HEALTH CENTRE
|ADAGBANGBA PRIMARY HEALTH CENTRE
|AGEDE PRIMARY HEALTH CENTRE
|KISI GENERAL HOSPITAL
 OYO	ISEYIN	ILADO PRIMARY HEALTH CARE CENTRE
|FARAMORA PRIMARY HEALTH CARE CENTRE
|ADO AWAYE PRIMARY HEALTH CARE CENTRE
|ISEYIN GENERAL HOSPITAL
|ISALU PRIMARY HEALTH CARE CENTRE
 OYO	ITESIWAJU	IGBOJAYE PRIMARY HEALTH CENTRE
|IPAPO COMPREHENSIVE HEALTH CENTRE
|KOMU PRIMARY HEALTH CENTRE
 OYO	IWAJOWA	IDIKO AGO PRIMARY  HEALTH CENTRE
|ILAJI ILE PRIMARY  HEALTH CENTRE
|IWERE ILE GENERAL HOSPITAL
|IJIO PRIMARY HEALTH CENTRE
|ELEKOKAN PRIMARY HEALTH CENTRE
OYO	KAJOLA	IJO PRIMARY HALTH CENTRE
| PRIMARY HEALTH CENTRE
|BODE PRIMARY HEALTH CENTRE
|AGBAGI PRIMARY HEALTH CENTRE
 OYO	LAGELU	LAGUN GENERAL HOSPITAL
|APATERE PRIMARY HEALTH CLINIC
|EJIOKU PRIMARY HEALTH CENTRE
|ALEGONGO PRIMARY HEALTH CENTRE
|AKOBO NAVAL AIR FORCE MEDICAL CENTRE
 OYO	OGBOMOSHO NORTH 	OSUPA HEALTH CENTRE
|IBRAHIM TAIWO PRIMARY HEALTH CENTRE
|JAGUN PRIMARY HEALTH CENTRE
|TARAA PRIMARY HEALTH CENTRE
|BAAKI PRIMARY HEALTH CENTRE
 OYO	OGBOMOSHO SOUTH 	IJERU PRIMARY HEALTH CENTRE
|OKE OOLA HEALTH POST
|ALABEDE PRIMARY HEALTH CENTRE
 OYO	OGO OLUWA	AJAAWA MODEL PRIMARY  HEALTH CENTRE
|IDEWURE PRIMARY HEALTH CENTRE
|LAGBEDU PRIMARY  HEALTH CENTRE
|IWO-ATE PRIMARY HEALTH CENTRE
|AYEDE PRIMARY HEALTH CENTRE
 OYO	OLORUNSOGO	OJU OJA PRIMARY HEALTH CLINIC
|OKE-ABE PRIMARY HEALTH CENTRE
|MOTI PRIMARY  HEALTH CENTRE
|ASUNMODE PRIMARY HEALTH CENTRE
|OGUNTELA NLA HEALTH POST
 OYO	OLUYOLE	AYEGUN PRIMARY HEALTH CENTRE
|AYETORO PRIMARY HEALTH CLINIC
|BARE PRIMARY HEALTH CENTRE
|IDI-AYUNRE PRIMARY HEALTH CLINIC
 OYO	ONA -ARA	BADEKU PRIMARY HEALTH CENTRE
|AKANRAN PRIMARY HEALTH CENTRE
|AJIA PRIMARY HEALTH CENTRE
|AWOTUNDE OLOSUNDE PRIMARY HEALTH CENTER
 OYO	ORELOPE	MAFOWAKU PRIMARY HEALTH CENTRE
|MODEKE PRIMARY HEALTH CENTRE
|BONNI PRIMARY HEALTH CENTRE
|IGBOPE PRIMARY HEALTH CENTRE
 OYO	ORI-IRE	ADAFILA PRIMARY HEALTH CENTRE
|ALAROPO NLA PRIMARY HEALTH CENTRE
|IKOYI-ILE GENERAL HOSPITAL
|AHORO DADA PRIMARY HEALTH CENTRE
|ELESUN ADEOSUN PRIMARY HEALTH CENTRE
 OYO	OYO EAST	ALAWUSA PRIMARY HEALTH CENTRE
|AGBOYE PRIMARY HEALTH CENTRE
|OBA ADEYEMI PRIMARY HEALTH CENTRE
|JABATA PRIMARY HEALTH CENTRE
|IDI IYA PRIMARY HEALTH CENTRE
 OYO	OYO WEST	AKEETAN PRIMARY HEALTH CENTRE
|KOLOBO PRIMARY HEALTH CENTRE
|AJOKIDERO HEALTH POST
|ISEKE PRIMARY HEALTH CENTRE
|FASOLA PRIMARY  HEALTH  CENTRE
 OYO	SAKI EAST	GENERAL HOSPITAL SEPETERI
|AGO AMODU PRIMARY HEALTH CENTRE
|AGBONLE PRIMARY HEALTH CENTRE
|OGBOORO MODEL PRIMARY HEALTH CARE
 OYO	SAKI WEST	BAABO PRIMARY HEALTH CENTRE
|AJEGUNLE PRIMARY HEALTH CENTRE
|ADABO PRIMARY HEALTH CENTRE
|EKOKAN PRIMARY HEALTH CENTRE
|CHALLENGE PRIMARY HEALTH CENTRE
 OYO	SURULERE	IRESAAPA PRIMARY HEALTH CENTRE
|GAMBARI PRIMARY HEALTH CENTRE
|OIREGBA PRIMARY HEALTH CENTRE
|AROLU PRIMARY HEALTH  CENTRE
|BAAYA OJE PRIMARY HEALTH CENTRE
|
PLATEAU	BARKIN LADI	 KAPWIS PRIMARY HEALTH CENTRE
|MAI IDON TORO PHC5078
PLATEAU	BASSA	 ZAGUN PRIMARY HEALTH CENTRE
|AMOKATAKO PHC
|BUYO PHC
|DUNDU PHC
PLATEAU	BOKKOS	 KAMWAI PRIMARY HEALTH CENTRE
| MAIKATAKO PRIMARY HEALTH CENTRE
| DAFFO PRIMARY HEALTH CENTRE
| GWANDE PRIMARY HEALTH CENTRE
PLATEAU	JOS EAST	 ANGWARE PRIMARY HEALTH CENTRE
|NIJI PRIMARY HEALTH CENTRE
|KAYARDA PRIMARY HEALTH CENTRE
PLATEAU	JOS NORTH	 JENTA ADAMU PRIMARY HEALTH CENTRE
| ABBA NA SHEHU PRIMARY HEALTH CENTRE
| ANGWAN ROGO PRIMARY HEALTH CENTRE
|GANGARE  PRIMARY HEALTH CENTRE
|JENTA APATA PRIMARY HEALTH CENTRE
| JOS JARAWA PRIMARY HEALTH CENTRE
|KABONG PRIMARY HEALTH CENTRE
| LAMINGO PRIMARY HEALTH CENTRE
PLATEAU	JOS SOUTH	PHC BUKURU CENTRAL
|PHC CHIGWE
|PHC ANGOLO JOS
|PHC RAYFIELD
|PHC HWOLSHE
|PHC BUKURU EXPRESS
PLATEAU	KANAM	DENGI PHC
|GARGA PHC
|JARMAI PHC
|GAGDI TOWN PHC
PLATEAU	KANKE	DAWAKI PRIMARY HEALTH CENTRE
|TABULUNG PHC
|LANGSHI PHC
PLATEAU	LANGTANG NORTH	 LANGTANG PRIMARY HEALTH CENTRE
|NYER PHC
|GAZUM PHC
|TIPSIM PHC
PLATEAU	LANGTANG SOUTH	ANGUWAN MISSION PHC
|JEMKUR PHC
|TURAKI PHC
PLATEAU	MANGU	MANGU 1 PHC
|PANYAM PHC
|GINDIRI 2 PHC
|MANGUN PHC
PLATEAU	MIKANG	PHC TUNKUS
| PIAPUNG PRIMARY HEALTH CENTRE
|GARKAWA 2 PRIMARY HEALTH CENTRE
PLATEAU	PANKSHIN	PHC TOWN CLINIC
|TAKKAS PHC
|CHIP PHC
|ABWOR PHC
PLATEAU	QUAANPAN	KWANDE PHC
|DOEMAK PHC
|LARDAN PHC
|NAMU PHC
PLATEAU	RIYOM	RIYOM PHC
|RA-HOSS PHC
PLATEAU	SHENDAM	SHANDAM A PHC
|KALONG PHC
|YAMINI PHC
|YEDLWA EAST PHC
PLATEAU	WASE	MPHC BASHAR
|WASE TOFA PHC
|WASE PHC
|KADARKO PHC
|
RIVERS	PORT HARCOURT	RIVERS STATE UNIVERSITY TEACHING HOSPITAL
|OROGBUM CHC 
|OZUBOKO MODEL PRIMARY HEALTH CENTRE
|MILITARY HOSPITAL
|CHURCHILL MODEL PRIMARY HEALTH CENTRE
|MGBUNDUKWU MODEL PRIMARY HEALTH CENTRE
|ABULOMA PRIMARY HEALTH CENTRE
|SICK BAY CITY COUNCIL
|POTT JOHNSON MODEL PRIMARY HEALTH CENTRE
RIVERS	OBIO/AKPOR	EVERY WOMAN MEDICAL CENTRE
|ELEKAHIA MODEL PRIMARY HEALTH CENTRE
|RUMUIGBO MODEL PRIMARY HEALTH CENTRE
|UNIVERSITY OF PORT HARCOURT TEACHING HOSPITAL
|OZUOBA MODEL PRIMARY HEALTH CENTRE
|RUMUKRUSHI MODEL PRIMARY HEALTH CENTRE
|RUMUODOMAYA MODEL PRIMARY HEALTH CENTRE
|OBIO COTTAGE HOSPITAL (PRIMARY/SECONDARY)
|IRIEBE MODEL PRIMARY HEALTH CENTRE
|MGBOSHIMINI MODEL PRIMARY HEALTH CENTRE
RIVERS	ELEME	ONNE MODEL PRIMARY HEALTH CENTRE
|ELEME GENERAL HOSPITAL
|AGBONCHIA MODEL PRIMARY HEALTH CENTRE
|AKPAJO MODEL PRIMARY HEALTH CENTRE
|OGALE PRIMARY HEALTH CENTRE
RIVERS	BONNY	BONNY MODEL PRIMARY HEALTH CENTRE
|ZONAL HOSPITAL BONNY
|FINIMA PRIMARY HEALTH CENTRE
|PETERSIDE MODEL PRIMARY HEALTH CENTRE
|ABALAMABIE PRIMARY HEALTH CENTRE
RIVERS	TAI	NONWA MODEL PRIMARY HEALTH CENTRE
|KPITE MODEL PRIMARY HEALTH CENTRE
|KOROKORO PRIMARY HEALTH CENTRE
RIVERS	IKWERRE	OMAGWA PRIMARY HEALTH CENTRE
|ISIOKPO INFANT WELFARE CLINIC 
|MADONNA UNIVERSITY TEACHING HOSPITAL
|IGWURUTA PRIMARY HEALTH CENTRE
RIVERS	OYIGBO	OYIGBO COMPREHENSIVE HEALTH CENTRE
|MIRINWAYI MODEL PRIMARY HEALTH CENTRE
|UMUAGBAI MODEL PRIMARY HEALTH CENTRE
RIVERS	DEGEMA	ZONAL HOSPITAL DEGEMA
|DEGEMA COMPREHENSIVE HEALTH CENTRE
|OBUAMA MODEL PRIMARY HEALTH CENTRE
|BILLE PRIMARY HEALTH CARE CENTRE
|KE PRIMARY HEALTH CARE CENTRE
|OGURUAMA MODEL PRIMARY HEALTH CARE CENTRE
|TOMBIA COMPREHENSIVE HEALTH CENTRE
RIVERS	KHANA	BORI MODEL PRIMARY HEALTH CENTRE
|ZONAL HOSPITAL BORI
|BANE MODEL PRIMARY HEALTH CENTRE
|WIIYAAKARA MODEL PRIMARY HEALTH CENTRE
RIVERS	OKRIKA	OKRIKA GENERAL HOSPITAL
|OGOLOMA MODEL PRIMARY HEALTH CENTRE
|ISAKA PRIMARY HEALTH CARE CENTRE
|OKUJAGU PRIMARY HEALTH CARE CENTRE
|OKOCHIRI MODEL PRIMARY HEALTH CENTRE
|IBAKA MODEL PRIMARY HEALTH CARE CENTRE
RIVERS	ETCHE	OKOMOKO GENERAL HOSPITAL INFANT WELFARE CLINIC
|EGWI PRIMARY HEALTH CENTRE
|GRASSROOT/ NDASHI PRIMARY HEALTH CENTRE
|CHOKOCHO PRIMARY HEALTH CENTRE
RIVERS	OGBA/EGBEMA/NDONI	OMOKU MODEL PRIMARY HEALTH CENTRE
|OMOKU GENERAL HOSPITAL
|ASE-ASAGA MODEL PRIMARY HEALTH CARE CENTRE
|NDONI COMPREHENSIVE HEALTH CENTRE
|OKWUZI MODEL PRIMARY HEALTH CENTRE
RIVERS	AHOADA EAST	AHOADA MODEL PRIMARY HEALTH CENTRE
|AHOADA GENERAL HOSPITAL
|IHUABA PRIMARY HEALTH CENTRE
|IHUAMA MODEL PRIMARY HEALTH CENTRE
RIVERS	EMOUHA	NDELE MODEL PRIMARY HEALTH CENTRE
|EMOHUA INFANT WELFARE CLINIC
|RUMUJI PRIMARY HEALTH CENTRE
RIVERS	GOKANA	TERABOR GENERAL HOSPITAL
|TERABOR PRIMARY HEALTH CENTRE
|KPOR MODEL PRIMARY HEALTH CENTRE
|MOGHO PRIMARY HEALTH CENTRE
|BODO GENERAL HOSPITAL
RIVERS	ASARI-TORU	BUGUMA MODEL PRIMARY HEALTH CENTRE
|ABALAMA MODEL PRIMARY HEALTH CENTRE
|IFOKO PRIMARY HEALTH CARE CENTRE
|KRAKRAAMA PRIMARY HEALTH CARE CENTRE
|ANGULAMA PRIMARY HEALTH CENTRE
|BUGUMA GENERAL HOSPITAL
RIVERS	OGU/BOLO	OGU MODEL PRIMARY HEALTH CENTRE
|IWOGONO PRIMARY HEALTH CARE CENTRE
|OPU-AMA PRIMARY HEALTH CARE CENTRE
|BOLO COMPREHENSIVE HEALTH CENTRE
|OGU GENERAL HOSPITAL
|IKPO-AMA HEALTH CENTRE
RIVERS	ABUA/ODUAL	AYAMA PRIMARY HEALTH CENTRE 
|ABUA GENERAL HOSPITAL 
|ANYU MODEL PRIMARY HEALTH CENTRE
|EMAGO-KUGBO PRIMARY HEALTH CARE CENTRE
|OGBEMA MODEL PRIMARY HEALTH CENTRE
|AMINIGBOKO COTTAGE HOSPITAL
RIVERS	AHOADA WEST	AKINIMA MODEL PRIMARY HEALTH CENTRE
|EDAGBERI COTTAGE HOSPITAL
|OKARKI MODEL PRIMARY HEALTH CENTRE
|OKOGBE PRIMARY HEALTH CENTRE
RIVERS	AKUKU- TORU	ABONNEMA GENERAL HOSPITAL
|ABONNEMA MODEL PRIMARY HEALTH CENTRE 
|OBONOMA MODEL PRIMARY HEALTH CENTRE
|ABISSA PRIMARY HEALTH CARE CENTRE
|ELEM-SANGAMA PRIMARY HEALTH CARE CENTRE
|IDAMA PRIMARY HEALTH CARE CENTRE
|KULA MODEL PRIMARY HEALTH CENTRE
RIVERS	ANDONI	ASARAMA PRIMARY HEALTH CENTRE
|NGO PRIMARY HEALTH CENTRE
|IKURU TOWN MODEL PRIMARY CARE CENTRE
|IBOTIREM PRIMARY HEALTH CARE CENTRE
|EBUKUMA PRIMARY HEALTH CARE CENTRE
|ATABA COMPREHENSIVE HEALTH CENTRE
RIVERS	OMUMA	EBERI PRIMARY HEALTH CENTRE
|OYORO MODEL HEALTH CENTRE
|UMUAJULOKE PRIMARY HEALTH CENTRE
RIVERS	OPOBO/NKORO	OPOBO MODEL PRIMARY HEALTH CENTRE
|NKORO MODEL PRIMARY HEALTH CENTRE
|QUEENS TOWN MODEL PRIMARY HEALTH CARE CENTRE
|EPELEMA PRIMARY HEALTH CARE CENTRE
|KALAIBIAMA PRIMARY HEALTH CENTRE
|
SOKOTO	BINJI 	BINJI GENERAL HOSPITAL
SOKOTO	BODINGA 	BODINGA GENERAL HOSPITAL
|DINGYADI PRIMARY HEALTH CENTER
SOKOTO	DANGE-SHUNI 	SHUNI UPGRADED HEALTH CLINIC
|DANGE MODEL PRIMARY HEALTH CENTER
|KWANNAWA PRIMARY HEALTH CLINIC
SOKOTO	GADA 	GADA GENERAL HOSPITAL
|WAURU PRIMARY HEALTH CARE CENTER
SOKOTO	GORONYO 	GORONYO GENERAL HOSPITAL
|GORAU HEALTH POST
SOKOTO	GUDU 	GENERAL HOSPITAL BALLE
SOKOTO	GWADABAWA 	GWADABAWA GENERAL HOSPITAL
SOKOTO	ILLELA 	ILLELA GENERAL HOSPITAL
SOKOTO	ISA 	ISA GENERAL HOSPITAL
SOKOTO	KEBBE 	KEBBE GENERAL HOSPITAL
|KUCHI PRIMARY HEALTH CENTER
SOKOTO	KWARE 	KWARE PRIMARY HEALTH CENTRE
|DURBAWA PRIMARY HEALTH CENTER
SOKOTO	RABAH 	RABAH GENERAL HOSPITAL
|YARTSAKUWA PRIMARY HEALTH CENTER
SOKOTO	SABON 	SABON BIRNI GENERAL HOSPITAL
|KURAWA PRIMARY HEALTH CENTER
SOKOTO	SHAGARI L	SHAGARI GENERAL HOSPITAL
|KAJIJI MODEL PRIMARY HEALTH CENTER
SOKOTO	SILAME 	SILAME GENERAL HOSPITAL
SOKOTO	SOKOTO NORTH 	SO SOKOTO NORTH WOMEN AND CHILD WELFARE CLINIC
|HELELE PRIMARY HEALTH CENTER
| ALKAMMAWA PRIMARY HEALTH CENTER
|KOFAR KADE PRIMARY HEALTH CENTER
SOKOTO	SOKOTO SOUTH 	SOKOTO SPECIALIST HOSPITAL
|GIDAN DAHALA PRIMARY HEALTH CENTER
|MABERA BASIC HEALTH CLINIC
| YAR AKIJA BASIC HEALTH CLINIC
SOKOTO	TAMBUWAL 	TAMBUWAL GENERAL HOSPITAL
|DOGAN DAJIGENERAL HOSPITAL
SOKOTO	TANGAZA 	TANGAZA GENERAL HOSPITAL
SOKOTO	TURETA 	GENERAL HOSPITAL TURETA 
SOKOTO	WAMAKO 	ARKILLA PRIMARY HEALTH CENTRE
|USMAN DAFODIO TEACHING HOSPITAL
|ORTHOPEDIC HOSPITAL
SOKOTO	WURNO 	WURNO GENERAL HOSPITAL
|ACHIDA MODEL PRIMARY HEALTH CENTER
SOKOTO	YABO 	GENERAL HOSPITAL YABO
|
TARABA	ARDO KOLA	SUNKANI PHCC
TARABA	BALI	BALI PHCC
|GABACHEDE PHCC
|DAKA PHCC
TARABA	DONGA	MARABA PHCC
|FIRST REFERAL
TARABA	GASHAKA	ALFA PHCC
|FIRST REFERAL SATI
TARABA	GASSOL 	MUTUM BIYU PHCC
|JAURO MANU PHCC
|GASSOLPHCC
|TELLA PHCC
TARABA	IBI	IBI TOWNSHIP PHCC
TARABA	JALINGO	TURAKI A PHCC
|FMC
|POLICE CLINIC
|NEW BARADE PHCC
TARABA	KARIM LAMIDO	KARIM PHCC
|JEN PHCC
|KARIM PHCC
TARABA	KURMI	ABONG PHCC
TARABA	LAU	LAU PHCC
TARABA	SARDAUNA	GENERAL HOSP GEMBU 
|MAMBILA BAPTIST
TARABA	TAKUM	GENERAL HOSP TAKUM
|CHANCHANGI PHCC
|GENERAL HOSPITAL 
|SABON GIDA YUKUBEN
TARABA	USSA	JENUWA PHCC
TARABA	WUKARI	WAPAN AGHAKU PHCC
|GENERAL HOSPITAL WUKARI
|BETHEL HOSPITAL
|BANTAJE PHCC
TARABA	YORRO	PANTISAWA PHCC
TARABA	ZING	ZING PHCC
|
YOBE	BADE	GENERAL HOSPITAL GASHUA, SABON GARI WARD
|KATUZU PHCC, KATUZU WARD
YOBE	BURSARI	GENERAL HOSPITAL DAPCHI, DAPCHI WARD
|JAWA PHCC, JAWA/GARUN DOLE WARD
YOBE	DAMATURU	STATE SPECIALIST HOSPITAL DAMATURU CENTRAL WARD
|GWANGE PHCC, NJIWARI/GWANGE WARD
|NAYI-NAWA PHCC, NAYINAWA WARD
|WOMEN & CHILDREN HOSPITAL, BINDIGARI/PAWARI WARD
YOBE	FIKA	GENERAL HOSPITAL FIKA, FIKA ANZE WARD
|GADAKA PHCC, GADAKA SHAMBE WARD
|JANGA PHC, JANGA WARD
YOBE	FUNE	GENERAL HOSPITAL, DAMAGUM A WARD 
|JAJERE PHCC, JAJERE WARD
YOBE	GEIDAM	GENERAL HOSPITAL GEIDAM, HAUSARI WARD
|ASHEKIRI PHC, ASHEKERI WARD
YOBE	GUJBA	SPECIALIST HOSPITAL, BUNI YADI WARD
|WAGIR PHCC, WAGIR WARD
YOBE	GULANI	BARA PHCC, BARA WARD
|GULANI PHCC, GULANI WARD
YOBE	JAKUSKO	GENERAL HOSPITAL, JAKUSKO WARD
|BUDUWA PHCC, BUDUWA WARD
|MUGURAM PHCC, MUGURU WARD
YOBE	KARASUWA	JAJIMAJI PHCC, JAJIMAJI WARD
|KARASUWA GARIN GUNA PHCC, KARASUWA GG WARD
YOBE	MACHINA	MACHINA PHCC, MACHINA WARD
|FALIMERAM PHCC, FALIMERAM WARD
YOBE	NANGERE	GENERAL HOSPITAL NANGERE, NANGERE WARD
|TIKAU PHCC, TIKAU WARD
YOBE	NGURU	BULABULIN PHCC, BULABULIN WARD
|SABON GARIN KANURI PHCC, SABON GRAI KANURI WARD
YOBE	POTISKUM	SPECIALIST HOSPITAL POTISKUM, HUSAUSAWA ASIBITI WARD
|DOGON ZARE PHCC, BOLEWA B WARD
|YERIMARAM PHCC, YERIMARAM WARD
YOBE	TARMUWA	BABBANGIDA PHCC, BABBANGIDA WARD
|CHIROKUSKO PHCC, BIRIRI WARD
YOBE	YUNUSARI	YUNUSARI PHCC, YUNUSARI WARD
|KALGI PHCC, DILALA/KALGI WARD
YOBE	YUSUFARI	YUSUFARI PHCC, YUSUFARI WARD
|MAYORI PHCC, MAYORI WARD
|
ZAMFARA	ANKA	GENERAL HOSPITAL  ANKA
|PHC BAGEGA
|WCWC ANKA
ZAMFARA	BAKURA	GENERAL HOSPITAL BAKURA
|PHC NASARAWA
ZAMFARA	BIRNIN MAGAJI	PHC GORA
|PHC NASARAWA MAI LAYI
|GENERAL HOSPITAL BIRNIN MAGAJI
ZAMFARA	BUKKUYUM	GENERAL HOSPITAL BUKKUYUM
|PHC NASARAWA
|PHC GADARZAIMA
ZAMFARA	BUNGUDU	GENERAL HOSPITAL BUNGUDU
|PHC KOTORKOSHI
|PHC NAHUCHE
ZAMFARA	GUMMI	GENERAL HOSPITAL GUMMI
|PHC DAKITAKWAS
|PHC GYALANGE
ZAMFARA	GUSAU	AHMED SANI YARIMAN BAKURA
|OLPC
|PHC DAMBA
|GENERAL HOSPITAL MAGAMI
ZAMFARA	KAURA NAMODA	KHADIZA WCWC KAURA
|PHC KASUWAR DAJI
|GENERAL HOSPITAL KAURA
ZAMFARA	MARADUN	O.L.P.C MARADUN
|GENERAL HOSPITAL MARADUN
|PHC FARU
ZAMFARA	MARU	GENERAL HOSPITAL MARU
|PHC KANOMA
|GENERAL HOSPITAL DAN SADAU
ZAMFARA	SHINKAFI	WCWC SHINKAFI
|GENERAL HOSPITAL SHINKAFI
|GALADI PHC
ZAMFARA	TALATA MAFARA	GENERAL HOSPITAL TALATA MAFARA
|OLPC MAFARA
|PHC JANGEBE
ZAMFARA	TSAFE	GENERAL HOSPITAL TSAFE
|PHC BILBIS
ZAMFARA	ZURMI	ZURMI PHC
|DAURAN PHC
|MORIKI PHC
`

@Component({
  selector: 'app-vaccine-centers',
  templateUrl: './vaccine-centers.component.html',
  styleUrls: ['./vaccine-centers.component.scss']
})

export class VaccineCentersComponent implements OnInit {

  showHTML = false
  currentState = "ABIA"
  states = [
    'Select a state',
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Federal Capital Territory',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara'
];

  displayVaccineCenters:any[] = []

  populateArray() {
    const readLine = vaccine.split("\n")
    const re = /\|/g

    var index = 0
    readLine.forEach(line => {
      const getLine = line.split("	")
      const state = getLine[0]
      if(state === "|") {

      }else {
        
      }

      index = index + 1
    })
  }

  ngOnInit() {
    this.getVaccineCentersByState()
  }

  onStateChanged(evt:any) {
    if(evt.target.value === "Select a state") {
      return
    }
    this.currentState = `${evt.target.value}`.toUpperCase()
    this.getVaccineCentersByState()
  }

  getVaccineCentersByState() {

    this.displayVaccineCenters = []
  }

  formatNumbers(value: number, addCurrency:boolean = false) {
    const formatter = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'NGN',
      minimumFractionDigits: 2
    })
    const f = formatter.format(value)
    return (addCurrency) ? f : f.substring(4, f.length - 3)
  }
}
